### ISSUE TITLE
Check if exists before inserting

### ISSUE THREAD

**Issue by vikramjb** [StackExchange/Dapper#1020]
I am using Dapper.Contrib to do my inserts and updates and it works flawlessly. I was wondering if there is a way to add check in the "Insert" to see if the value in the primary key column already exists in the table where the insert is going to happen.

I searched around found that apart from writing "IF EXISTS" there is no other way. I am wondering if I have missed an obvious solution or a work around a configuration option.

**Comment by ekarayigit** [comment]
https://stackoverflow.com/questions/39006512/check-if-record-exists-with-dapper-orm

are you talking about this ?

**Comment by vikramjb** [comment]
Not really. That method will do it but was looking more at a solution that was part of the insert method of the contrib library. I was looking to write an extension to the insert method but was not sure how to do it.

**Comment by ekarayigit** [comment]
Are u finding new solution ? I can improve your issue on dapper but what is your suggest ?

**Comment by ekarayigit** [comment]
Do you want to improve extension on dapper repository ?

**Comment by vikramjb** [comment]
@Adondriel I understand, I worked around it using a condition in the SELECT statement itself. Thanks for the response.

**Comment by palenshus** [comment]
I believe there should be a _new_ method called something like `InsertIfNotExists` which only inserts if the row doesn't exist. This is a very common operation and it would be great if the library supports it. It could be done as a single SQL call instead of having to do it with two Dapper calls which would also be more efficient. The implementation would be something like https://stackoverflow.com/a/5288494/892770, but would use the `Id/[Key]` column to automatically do the existence check. If the owners are on board with this, please reopen the issue, or I can file a new one, thanks!
