### ISSUE TITLE
SqlMapper CollectCacheGarbage not working due to wrong limit

### ISSUE THREAD

**Issue by csnemes** [StackExchange/Dapper#1022]
In SqlMapper the garbage collection the hit count limit is compared to COLLECT_HIT_COUNT_MIN constant which is 0. As far as I see the actual hit count is at least 1 so it will never clean up the cache.

**Comment by NickCraver** [comment]
The hit count should really be thought of as the *re-use* count. Since `.RecordHit()` is only called *on subsequent usages*, the hit count is 0 for queries that are never re-used. Those are the ones getting garbage collected. Perhaps we should rename the variable, but the behavior is correct.

Are you seeing another issue downstream of this behavior we need to look at, or just curious?

**Comment by csnemes** [comment]
Ok, I need to dig bit deeper into this problem them. What I can actually see, is that in a memory dump I have hundreds of thousands cached queries all with hit count = 1. we don't use dapper directly, we use dapper crud to create parametrized queries, but unfortunately it seems that it turns them into separate ones. Although we query each item in our db once, based on your comment it seems that our app calls the query twice (hence the hitcount=1). I'll take a look on this. Anyway I'm wondering if it would be possible to create an extension point here to inject different collection strategies or at least specify the limit from the outside. In our situation where we query millions of items one-by-one after a certain time cache will eat up a lot of memory.

**Comment by NickCraver** [comment]
Do you have some code examples? From your description it sounds like something isn't being parameterized, which would explode both local and server-side query caches alike.

**Comment by csnemes** [comment]
As I mentioned we use Dapper.FastCRUD on top of Dapper. Here's an example with produces separate cache entries for each id:
 var mediaRecords = await connection.FindAsync<QueryMediaRecord>(statement
                    => statement.WithEntityMappingOverride(schemaSpecificMappingForQueryMedia)
                        .Where($"{nameof(QueryMediaRecord.DocumentId):C} = @id AND Deleted=0")
                        .WithParameters(new { Id = documentId })).ConfigureAwait(false);

**Comment by NickCraver** [comment]
@csnemes Can you show us the generated SQL that FastCRUD outputs (calls Dapper with)? The issue is on that side, if it's producing a different query for each ID. It's not a Dapper problem, but one layer up, if they're for example substituting the ID in instead of using a parameter as it should. In either case: this is a issue best suited for their repo, since the problem is not the size of the cache, but *that there are duplicates created at all*, with a growing cache being a symptom of that.

**Comment by csnemes** [comment]
Hi, it turned out that some of our code was shortcuting parametrization due to some strange behaviour/bug(?) in the FastCRUD library. But that's a different story. Anyway on the long run it would be nice to extend/change the eviction strategy. Thanks for all the help.
