### ISSUE TITLE
Pass parameters into Substring in Select statement

### ISSUE THREAD

**Issue by gdodd1977** [StackExchange/Dapper#1083]
I'm trying to execute this query:

`private string OptInQuery = @"SELECT 
                SUBSTRING(@OptInColumn,@StartIndex,1)
            FROM 
                SomeTable (NOLOCK) 
            WHERE 
                Key = @Key";`

This is my code:

`var optInValue = Execute<string>(OptInQuery,
                    new {
                            OptInColumn = carrierOptInMapping.OptInColumn,
                            StartIndex = carrierOptInMapping.OptInStartIndex,
                            Key = Key
                        }).FirstOrDefault();`

This isn't working though. When I replace the two params in the query string with hardcoded versions, it works. What am I missing here?

**Comment by mgravell** [comment]
Is that a column name? Column names and table names (etc) cannot be
parameterized. Your SQL simply tests whether the value of one parameter
matches / contains / etc the value of another parameter. To test a column,
the column name must be fixed in the SQL. Dapper does not support injection
of object names, as it presents a significant SQL Injection attack vector.

**Comment by gdodd1977** [comment]
Makes sense. Thanks for the quick response!
