### ISSUE TITLE
Error : each parameter can only be referenced once

### ISSUE THREAD

**Issue by ucandoit1010** [StackExchange/Dapper#1150]
Hi I have subquery in my sql script like this :

`SELECT * FROM XTABLE X , (SELECT * FROM ATABLE  WHERE ORG =: OID ) A 
WHERE X.ORG =: OID AND  A.ORG =: OID `

I am using [Query ](https://dapper-tutorial.net/query)execute SQL 
`new { OID = OID } `
 , but got error

`When passing parameters by position, each parameter can only be referenced once`

cany anyone guide me what's going on ? thank you .

**Comment by mgravell** [comment]
as it says: it is having to represent that using pseudo-positional mapping
of the parameters (which does surprise me, actually) - in which case it can
only use each "named" parameter once, because in reality it isn't named.
The trick, then, is to pass two different parameters with the same value
but different names.

**Comment by ucandoit1010** [comment]
THANK YOU .
we go it !

The problem is sql file without utf8 encoding,
but many chinese words in sql file !
event use oraclecommand still got error.
