### ISSUE TITLE
Simple INSERT with Dapper on Oracle

### ISSUE THREAD

**Issue by unipeg** [StackExchange/Dapper#1152]
Hi.

I would like to use Dapper to have db agnostic code used for e.g. PostgreSQL and Oracle with as little db flavored code as possible. This INSERT code is running without problems for SQL-server and PostgreSQL:

`var item = new Item { Name = "Test Name", Number = "Test Number" };`
`await Connection.ExecuteAsync(@"INSERT INTO Table (Name, Number) VALUES (@Name, @Number);", item);`

On Oracle (version 11 xe), I get an ORA-00936: missing expression.

Do I need tailoring using DynamicParameters or the likes?

**Comment by kelvindules** [comment]
Hello @unipeg.
Since this is using a **OracleCommand** of `CommandType.Text`, you should precede the parameter name with a colon (:).

That would look like:
```c#
var item = new Item { Name = "Test Name", Number = "Test Number" };
await Connection.ExecuteAsync(@"INSERT INTO Table (Name, Number) VALUES (:Name, :Number)", item)
```

Please [refer to the docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.oracleclient.oraclecommand.parameters?redirectedfrom=MSDN&view=netframework-4.7.2#System_Data_OracleClient_OracleCommand_Parameters) for greater details.

**Comment by NickCraver** [comment]
Answered above, closing out to cleanup!
