### ISSUE TITLE
IDataReader.Dispose messing with transaction

### ISSUE THREAD

**Issue by vqalves** [StackExchange/Dapper#1176]
Heya!
I'm using dapper within a .Net 4.6.1 web application, but sometimes it's messing with my transactions, leading to exceptions when we try to commit/rollback them.

I was able to map the exact line that's happening on the QueryImpl method, but have no idea what's going on.
![1 - OK Transaction](https://user-images.githubusercontent.com/1022382/51138191-9559eb00-1827-11e9-96c0-60bee24a26bf.png)
![2 - Bad Transaction](https://user-images.githubusercontent.com/1022382/51138193-9559eb00-1827-11e9-8e1f-65255548f85c.png)

Can I get some help?

**Comment by mgravell** [comment]
Can you define "messing with my transactions"? What is the actual symptom
here? Also: can I assume this was a connection-level transaction, as
opposed to an ambient transaction (aka TransactionScope)?

**Comment by stivehawk** [comment]
Woops, sorry for the lack of information!

Yes, you're correct. We're not using TransactionScope, because of DTC restrictions between our database servers.

Regarding the symptom, our production environment was logging some errors with _System.InvalidOperationException: This SqlTransaction has completed_ when calling transaction.Rollback(). Unfortunately I cannot share the code, but it executed something akin to that:

`using (var conn1 = new SqlConnection(CONNECTION_STRING_1))
using (var conn2 = new SqlConnection(CONNECTION_STRING_2))
{
	conn1.Open();
	conn2.Open();

	SqlTransaction tran1 = null;
	SqlTransaction tran2 = null;

	try
	{
		tran1 = conn1.BeginTransaction();
		tran2 = conn2.BeginTransaction();
	
		var value = conn1.Query<Output>
		(
			sql: "SELECT Value FROM Table1 WHERE Id = @id",
			param: new { id = 1 },
			transaction: tran1,
			buffered: false
		)
		.FirstOrDefault()? // This is where the transaction is lost
		.Number;

		var date2 = conn2.Query<Output>
		(
			sql: "INSERT INTO Table2 (Col) VALUES (@value)",
			param: new { value = value },
			transaction: tran2,
			buffered: false
		)
		.FirstOrDefault()?
		.CurrentDate;

		tran1.Commit();
		tran1 = null;

		tran2.Commit();
		tran2 = null;
	}
	finally
	{
		if(tran1 != null) tran1.Rollback(); // System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
		if(tran2 != null) tran2.Rollback();
	}
}`

Weirdly, it didn't always throw the exception. I never caught it during development, and was very hard to reproduce in production. Disclaimer: I never got that example code to throw the exception.

After I changed **conn1.Query&lt;Output&gt;** to SqlCommand / SqlDataReader, there were no more InvalidOperationExceptions.
