### ISSUE TITLE
Map int column as string

### ISSUE THREAD

**Issue by paulodiogo** [StackExchange/Dapper#1374]
I have an extremely dynamic component and in the case of queries I treat the types internally when I need. 

The types in the databases  can vary a lot in queries and the user writes it, so I use `Tuple<string, string>`. When I try to execute this query with Dapper when a type is not a string I receive an `InvalidCastException` in the face, is it possible for me to always return `string` or bypass the type check?

Today I am doing the following:
````
var data = connection.Query(query).ToList();

var result = data.Select(x =>
{
	var dic = ((IDictionary<string, object>)x);
	return new Tuple<string, string>(dic[key]?.ToString(), dic[value]?.ToString());
});
````

I don't know if it's clear. Thank you!

**Comment by mgravell** [comment]
I'm very unclear whether you're saying dapper is slow, or fast, or even whether speed is the issue here. Re the type check: there's no current way of bypassing that, but I wonder whether just getting the reader is more useful for your scenario. Dapper exposes an API that splits the work, with dapper dealing with the command, and your code dealing with the reader. Any use?

**Comment by paulodiogo** [comment]
> I'm very unclear whether you're saying dapper is slow, or fast, or even whether speed is the issue here. Re the type check: there's no current way of bypassing that, but I wonder whether just getting the reader is more useful for your scenario. Dapper exposes an API that splits the work, with dapper dealing with the command, and your code dealing with the reader. Any use?

Dapper is vary fast man hahaha, ok thank you!
