### ISSUE TITLE
@parameter not working

### ISSUE THREAD

**Issue by FatTigerWang** [StackExchange/Dapper#1375]
This code not working:
``` code
QueryFirstOrDefault<TEntity>( "SELECT * FROM Foo WHERE column1 = @column1 AND (GEOMETRY::STGeomFromText(Path, 0).MakeValid()).STContains(GEOMETRY::STGeomFromText('POINT(@longitude @latitude)', 0)) = 1",new {column1="", longitude = 0, latitude = 0});
```
exception:
A .NET Framework error occurred during execution of user-defined routine or aggregate "geography":
System.FormatException: 24141: A number is expected at position 16 of the input. The input has @longitude.
System.FormatException:
   at Microsoft.SqlServer.Types.OpenGisWktReader.RecognizeDouble()
   at Microsoft.SqlServer.Types.OpenGisWktReader.ParsePointText(Boolean parseParentheses)
   at Microsoft.SqlServer.Types.OpenGisWktReader.ParseTaggedText(OpenGisType type)
   at Microsoft.SqlServer.Types.OpenGisWktReader.Read(OpenGisType type, Int32 srid)
   at Microsoft.SqlServer.Types.SqlGeography.GeographyFromText(OpenGisType type, SqlChars taggedText, Int32 srid)
.
Look like not replace @parameter.

But this code is working:
``` code
QueryFirstOrDefault<TEntity>( "SELECT * FROM Foo WHERE column1 = @column1",new {column1=""});
```

**Comment by mgravell** [comment]
The problem here is nothing to do with dapper. The line:

``` sql
... '@foo,@bar' ...
```
is not "a string containing the *values* from the parameters `@foo` and `@bar`" (so, `'42, 6'`; it is "a string that contains at, f, o, o, comma, at, b, a, r". Strings are not interpreted with parameter injection in SQL.

So: there are three options here:

1. use an API that doesn't rely on strings, if one exists (no idea if there is a non-string geo factory)
2. use string concatenation in TSQL to build the geo factory string
3. use string concatenation in C# to build the geo factory string

If the numbers were always integers, there would be a fourth option - but I'm pretty sure we nailed it down just to integers. You could try it, though

4. use `{=foo}` instead of `@foo`; this is a Dapper-specific syntax that means "inject the value directly, using invariant formatting, instead of using a parameter". It is intentionally limited to specific types, to prevent SQL injection attack vectors

**Comment by FatTigerWang** [comment]
Thanks!
My value were always integers, so I use `{=foo}` instead of `@foo` .
It work.
