### ISSUE TITLE
SqlMapper Query param empty list cause table scan in mysql

### ISSUE THREAD

**Issue by caozhiyuan** [StackExchange/Dapper#1379]
https://github.com/StackExchange/Dapper/blob/master/Dapper/SqlMapper.cs#L2070

 connection.Query(
                    "Select  xxx from `test`   WHERE messageid IN @messageids;",
                    new {messageids = new List<int>()});
will gen sql Select  xxx from `test`   WHERE messageid IN (SELECT NULL WHERE 1 = 0)
explain sql show it scan all rows.

**Comment by deleteLater** [comment]
@caozhiyuan hello :raised_hand_with_fingers_splayed: can u share how you solve this problem

**Comment by jayrowe** [comment]
I ran into this today after I upgraded to mysql 8-compatible aurora (AWS). Everything seemed fine until I realized it was table scanning a bunch of tables (for other reasons). I spent some time digging into it and discovered this issue along the way.

It appears to only be an issue with a naked `SELECT ... WHERE` with no `FROM`.

Having a `FROM` clause with literally anything in it appears to fix the issue - a real table, a silly select, or the MySql 8.0.19+ table constructor `VALUES ROW(...)` syntax all work.

```
mysql> -- this is what Dapper does
mysql> EXPLAIN SELECT * FROM MyTable WHERE Id IN (SELECT NULL WHERE 1 = 0);
+----+--------------------+---------+------------+------+---------------+------+---------+------+--------+----------+------------------+
| id | select_type        | table   | partitions | type | possible_keys | key  | key_len | ref  | rows   | filtered | Extra            |
+----+--------------------+---------+------------+------+---------------+------+---------+------+--------+----------+------------------+
|  1 | PRIMARY            | MyTable | NULL       | ALL  | NULL          | NULL | NULL    | NULL | 462208 |   100.00 | Using where      |
|  2 | DEPENDENT SUBQUERY | NULL    | NULL       | NULL | NULL          | NULL | NULL    | NULL |   NULL |     NULL | Impossible WHERE |
+----+--------------------+---------+------------+------+---------------+------+---------+------+--------+----------+------------------+
2 rows in set, 1 warning (0.00 sec)

mysql> SELECT * FROM MyTable WHERE Id IN (SELECT NULL WHERE 1 = 0);
Empty set (0.88 sec)

mysql> -- this is better on mysql
mysql> EXPLAIN SELECT * FROM MyTable WHERE Id IN (SELECT NULL FROM (SELECT NULL) n WHERE 1 = 0);
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
| id | select_type | table | partitions | type | possible_keys | key  | key_len | ref  | rows | filtered | Extra            |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
|  1 | SIMPLE      | NULL  | NULL       | NULL | NULL          | NULL | NULL    | NULL | NULL |     NULL | Impossible WHERE |
+----+-------------+-------+------------+------+---------------+------+---------+------+------+----------+------------------+
1 row in set, 1 warning (0.00 sec)

mysql> SELECT * FROM MyTable WHERE Id IN (SELECT NULL FROM (SELECT NULL) n WHERE 1 = 0);
Empty set (0.00 sec)
```

Literally any valid `FROM` clause appears to fix it.

It seems like this is just something that should be fixed in MySql for sure. In the meantime is there a way to intercept the Dapper-generated IN clause to replace it with something different? 

Currently Dapper produces something like this:

```
SELECT * FROM MyTable WHERE ID IN (SELECT @originalParameterName WHERE 1 = 0);
```

and not:

```
SELECT * FROM MyTable WHERE ID IN (SELECT NULL WHERE 1 = 0);
```

I could fixup the latter pretty trivially myself but the former is difficult to detect. I'm assuming the parameter name is used as a placeholder to avoid something annoying like having to adjust positional parameters or something like that? Dapper jams `NULL` in as the parameter value anyway, so it seems pretty pointless.

It looks like this is coming from line ~2129 in `SqlMapper.cs` (`PackListParameters` method):

```
return "(SELECT " + variableName + " WHERE 1 = 0)";
```
