### ISSUE TITLE
Asp.net core 2.2 api not able to integrate miniprofiler, dapper and mySql to work 

### ISSUE THREAD

**Issue by farhad-taran-cko** [StackExchange/Dapper#1380]
I am trying to get miniprofiler and Dapper on MySql to work together to profile sql statements.

I have managed to get miniprofiler and swagger to work together but the sql generated and executed by dapper are not intercepted for some reason, I believe this is because Miniprofiler.Current always returns null for some reason.

I was wondering if anyone else can help.

sample project is attached.
run docker compose and run api manually.
![2](https://user-images.githubusercontent.com/50828745/69482142-8b255780-0e0f-11ea-9834-b08ef6664c8b.jpg)
![1](https://user-images.githubusercontent.com/50828745/69482148-8d87b180-0e0f-11ea-9d06-e6cc4515fd29.PNG)
[TestApi.zip](https://github.com/MiniProfiler/dotnet/files/3882683/TestApi.zip)

**Comment by NickCraver** [comment]
I see in your app you have:
```cs
            app.UseMvc();
            app.UseMiniProfiler();
```
This means MiniProfiler isn't starting to profile until after MVC has executed in the pipeline. It also means the fix is pretty easy, just reverse those lines :)

In short: `.UseMiniProfiler()` should come before the other things you want to profile since it "wraps" them the way middleware works.

**Comment by NickCraver** [comment]
I'm going to close this out since it's a MiniProfiler issue over at https://github.com/MiniProfiler/dotnet/issues/439 :)
