### ISSUE TITLE
.net core 3.1+dapper2.0.3 pool size use all

### ISSUE THREAD

**Issue by gaojiandonggg** [StackExchange/Dapper#1402]
I set the maximum number of threads is 512, and now I do stress testing with jmeter, I set up in 200 the number of threads started to access an interface, this interface is a single table query, I monitor database links created only 16, without executing SQL statements, such as dozens of seconds, an error, my program using the docker in Linux running in a container, there is no problem in the Windows environment, under Linux is problematic

.net core 3.1  +dapper 2.0.3

Error message is:
Input:;Message:Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

Think you  help me

**Comment by mgravell** [comment]
the number of threads is unrelated to the size of the connection pool; it sounds like you've simply exhausted the pool; this is usually due to one of 2 things:

1. you're leaking connections somewhere, i.e. not disposing them (often achieved via the `using` keyword in C#)
2. you genuinely have an awful lot of things going on, but haven't leaked the connections - they're just still open

You usually solve 1 by making sure you're disposing things. You usually solve 2 by releasing connections *if they aren't actually needed while other things go on* - for example, if your workload is:

- get connection
- query DB
- perform external web-requests based on data
- update DB
- release connection

then consider instead

- get connection
- query DB
- release connection
- perform external web-requests based on data
- get connection
- update DB
- release connection

Note that nothing in here is usually Dapper related, since Dapper *does not* manage your connection life-cycle - you pass your connection *into* dapper, and handle it all externally.

But emphasis again: forget about threads; this is unlikely to be a threading issue.

That said: one way it *can* tie into threads is if you are doing lots of async work, and you've caused a "spiral of death", i.e. tasks are being created faster than they are completing, causing exhaustion, with that exhaustion meaning that your async data access never completes, so never released the connection. The fix here is to find your "spiral of death" and fix it. Hard to advise on that without *lots* more context (context that I'm not volunteering to try and gather - it requires in-depth knowledge of your code-base)

**Comment by gaojiandonggg** [comment]
private SqlConnection Connection
        {
            get
            {
                    return new SqlConnection(_connectionString);
                
            }
        }

private void Execute(Action<SqlConnection, SqlTransaction> action)
        {
            var connection = this.Connection;
            var tran = this.Tran;

            try
            {
                action(connection, tran);
            }
            finally
            {
                if (tran == null)
                {
                    connection.Dispose();
                }
            }
        }

call the instance:
 return await this.Execute(async (connection, tran) =>
            {
                return (await connection.QueryAsync<T>(sql, parms, tran, _commandTimeout)).ToList();
            });
There should be no link leak in this way？



I can understand what you mean: 200 requests come at the same time, only a few worker threads have created the database link, the database link queries the data, has not returned the data, the subsequent requests come again, causing the problem?

**Comment by mgravell** [comment]
k, there's a few things I'd look at in this code

- have a *property getter* that returns a **new** `SqlConnection` is actively dangerous - properties are usually side-effect free and repeatedly callable
- it is very unclear what should happen if you *do* have a transaction - or even how this should work; ADO.NET transactions act inside a connection, so it really doesn't make sense to get a transaction if you've just obtained a **new** connection
- also, since you aren't opening the connection manually, Dapper is handling the open/close; it *doesn't make sense* to talk about transactions if you aren't also handling your own open/close, as Dapper will open/close the connection *when it needs*, which is not compatible with a spanning transaction
- I wonder what `.Tran` does, too!
- the `Action<...>` shown is not compatible with the code shown; since this is `async`, it would need to be `Func<SqlConnection, SqlTransaction, Task>` or similar; did you copy the wrong method?
- `ConfigureAwait`

The transaction stuff here is way to unclear to even begin to decipher, but if this was me, my first step might be something like:

``` c#
private SqlConnection CreateConnection() => new SqlConnection(_connectionString);
private async Task<List<T>> ExecuteAsync<T>(Func<SqlConnection, SqlTransaction, Task<List<T>>> operation)
{
    using (var connection = this.CreateConnection())
    {
        // note: I'm not even going to try to decipher the transaction bits
        return await operation(connection, tran).ConfigureAwait(false);
    }
}
```

with usage:

``` c#
var list = await ExecuteAsync(async (conn, tran) =>
    await conn.QueryAsync<T>(sql, params, tran, _commandTimeout)).ToList());
```

But again, I haven't seen anything so far that says "this is something to do with Dapper"

**Comment by NickCraver** [comment]
Closing out to cleanup - answers above!
