### ISSUE TITLE
Different results between Dapper and query in PostgreSQL db client 

### ISSUE THREAD

**Issue by Syltty** [StackExchange/Dapper#1417]
Hi,

I have a query which looks like this:

```
select t1.bla, t1.bla2, t1.bla3, t2.foo
from table1 t1
left join tableO o on o.key=t1.key and o.title=t1.title
left join tablet2 t2 on t1.key=t2.key and t1.field=t2.field
where o.key is null and t1.key is not null
```

Using Dapper it returns 538 rows.
Using db client (DBeaver) it returns 109 rows.

When running a simpler query it returns the same number of rows.

What the heck?

Thank you.

**Comment by mgravell** [comment]
Well, which is he *correct* number of rows? Is this perhaps an ansi-settings thing? (Meaning: how does null equality work; null equals null? Or nulls not equal? There are difference of opinion on this topic)

However! Dapper doesn't do anything to your query except run it. Happy to help you track down the reason, but I'm 99%+ sure that the reason isn't "because Dapper".

**Comment by Syltty** [comment]
Thank you for your quick answer!  I didn't say it was Dapper fault :D  

Correct number of rows is 109.

I tried with this statement upstream but it didn't help.
`Dapper.SqlMapper.AddTypeMap(typeof(string), System.Data.DbType.AnsiString);`

I activated query logging and I maybe have a lead:

from Dbeaver

> 2020-03-02 13:45:01 UTC-5e5d0ddd.cf954-STATEMENT:  **set client_encoding='utf8'** <==
> 2020-03-02 13:45:03 UTC-5e5d0ddf.d1698-DEBUG:  loaded library "pg_stat_statements"
> 2020-03-02 13:45:03 UTC-5e5d0ddf.d1698-DEBUG:  loaded library "eventlogger"
> 2020-03-02 13:45:03 UTC-5e5d0ddf.d1698-DEBUG:  loaded library "connection_throttle"
> 2020-03-02 13:45:03 UTC-5e5d0ddf.d1698-DEBUG:  loaded library "pg_qs"
> 2020-03-02 13:45:03 UTC-5e5d0ddf.d1698-DEBUG:  loaded library "pgms_wait_sampling" 
> 

from C#/Dapper

> 2020-03-02 13:47:56 UTC-5e5d0e8c.d174c-DEBUG:  loaded library "pg_stat_statements"
> 2020-03-02 13:47:56 UTC-5e5d0e8c.d174c-DEBUG:  loaded library "eventlogger"
> 2020-03-02 13:47:56 UTC-5e5d0e8c.d174c-DEBUG:  loaded library "connection_throttle"
> 2020-03-02 13:47:56 UTC-5e5d0e8c.d174c-DEBUG:  loaded library "pg_qs"
> 2020-03-02 13:47:56 UTC-5e5d0e8c.d174c-DEBUG:  loaded library "pgms_wait_sampling"
¨
Any idea?

**Comment by mgravell** [comment]
The `client_encoding` would be set on the connection string, so: it could be worth *trying*, that; assuming you're using `Npgsql`, [see here](https://www.npgsql.org/doc/connection-string-parameters.html) for reference (search on that page for `client_encoding`, it is there).

If that doesn't work...

Since there's no parameters to that query, I'm not quite sure how the client-encoding would matter; that might be the cause if you were, say, not getting the right text matches, or if text columns were coming back garbled.

I'm actually a little confused by your query, because you have `where o.key is null` *and* you have `on o.key=t1.key` - so if that join is *ever* working, it again: suggests an ANSI NULL behavior. However! I *suspect* that this is really a question for whichever ADO.NET provider you're using - again presumably `Npgsql` - because: Dapper isn't inventing the extra rows out of whole cloth - it is just exposing what the ADO.NET provider gives it..

**Comment by Syltty** [comment]
ok you were right. Pb was on the query: one table had a **timestampz** column while the other had a **date** column. t1.field=t2.field could not work.
Weird thing is that Dbeaver is able to implicitly cast one to another.

Thank you Marc!
