### ISSUE TITLE
Type conversion exception.

### ISSUE THREAD

**Issue by tinylit** [StackExchange/Dapper#1440]
When the aggregate function is executed and the return value is a value type, a type conversion exception is thrown on line 1200 of SqlMapper.
```csharp
if (val == null || val is T)
  {
       result = (T)val;
  }
```
Proposed adjustment to.
```csharp
if ( val is T)
  {
       result = (T)val;
  } else if(val == null){
      result = default(T);
 }
```

**Comment by NickCraver** [comment]
Do you have an example of what's throwing this? It sounds like you may be using a non-nullable type when handling a null return - it's expected that it wouldn't work rather than silently defaulting in that case.

**Comment by tinylit** [comment]
```csharp
        [Fact]
        public void TestAggregationFunctionValueType()
        {
            SqlMapper.PurgeQueryCache();

            var data = connection.QueryFirstOrDefault<int>(@"
declare @data table(Id int not null, A int null, B int null, C varchar(20), D int null, E int null)
insert @data (Id, A, B, C, D, E) values 
	(1,null,null,null,null,null),
	(2,42,42,'abc',2,2)
select max(A) from @data where Id=3");
        }
```

**Comment by tinylit** [comment]
Similarly, an exception is thrown if no record satisfies the condition.

**Comment by NickCraver** [comment]
Got it, thanks so much for the example! Always helps a ton.

Okay so overall: this is working as intended right now _in terms of breaking_. Casting _null_ to `int` does not yield a `default`. It's explicit that we match user expectations and that they can tell the difference between *no records* and *an invalid record*. A good example came up when polling about this, it's the difference between:
```c#
new int[] { }.FirstOrDefault();
```
...and what we're really dealing with here:
```
new int[] { null }.FirstOrDefault();
```
(which of course doesn't even compile). Other cases such as a string to 

So in all, I don't think we should change the behavior here. It's both (potentially) breaking and obfuscates the difference between the use cases. But the error sucks, and we can do better there to instruct users that they'll want to use `.QueryFirstOrDefault<int?>` instead to handle nulls. Today, we do handle this if it's _within a class_. For example:
![image](https://user-images.githubusercontent.com/454813/80915099-e09a5480-8d1d-11ea-9861-107838ea2466.png)

I'm going to poke at options here, since this has come up a bit and see what we can do without affecting performance too much.

**Comment by NickCraver** [comment]
Working on this in #1453 if curious!
