### ISSUE TITLE
Integration with AWS X-Ray

### ISSUE THREAD

**Issue by davidkeaveny** [StackExchange/Dapper#1444]
Is there any guidance on how to integrate Dapper with AWS X-Ray, in particular through their `TraceableSqlCommand` (https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-dotnet-sqlqueries.html) ? 

There's an open issue with the the X-Ray SDK to move to the use of `DiagnosticsSource` instead (https://github.com/aws/aws-xray-sdk-dotnet/issues/6) but there hasn't been much progress on that front in the past few years.

**Comment by NickCraver** [comment]
We can't do this in the library, but you can! Unfortunately, it's not trivial (and there are tradeoffs). The way that ADO.NET makes this pluggable is [via `DbConnection.CreateCommand()`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.createcommand?view=netcore-3.1). You'd want your `DbConnection` to call their method instead.

The problem is you can't inherit from `SqlConnection` and you need to wrap _everything_. For an example of how this is done (you can only wrap what you need, to slim down), [see how MiniProfiler does it for `ProfiledDbConnection`](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/Data/ProfiledDbConnection.cs). For example, [right here](https://github.com/MiniProfiler/dotnet/blob/master/src/MiniProfiler.Shared/Data/ProfiledDbConnection.cs#L158).

We're using MiniProfiler for similar purposes, but everything's done at the connection level instead of every command. I don't really think their API completely thought through actual usage considerations since that's painful _everywhere_ (or everyone has to wrap it), but...that's what they did :-/ I hope this helps though!

**Comment by davidkeaveny** [comment]
Unfortunately the X-Ray integration has proved to be quite problematic, as it breaks DevExpress Reporting v17.1, which is a critical component in our software, so we've had to roll back our integration plans for now.
