### ISSUE TITLE
Is there a pattern Dapper allows its users to use, which does not propagate exceptions?

### ISSUE THREAD

**Issue by SpiritBob** [StackExchange/Dapper#1482]
Exception handling is slow.

Imagine having a stored procedure that has custom logic integrated by making various checks on the data you're supplying. If it's not happy - it will return an error. That error in Dapper is propagated as an exception, and you'll have to handle it.

Is there an alternative to Dapper propagating the exception, to maybe returning a bool if the operation was successful or not, or perhaps a much much better approach - a string object containing the error message returned by the procedure (string.Empty/null if no error was returned)?

Thank you for this great library. Looking forward to hearing from you!

**Comment by mgravell** [comment]
> Exception handling is slow.

That is a common misconception. It isn't anything like as slow as people imagine. It *is* a relevant discussion for CPU-centric loops, such as frame parsing (`TryParse` vs `Parse` + `catch`, being the classic example), but it is *almost entirely irrelevant* here:

- we are already in exception-aware blocks, due to the need to dispose various command/reader/etc objects
- you are almost always talking out-of-process, and usually: off-box

so: any "slowness" in exception handling is *barely even noise*; in a quick check locally:

> 500000 caught in 4448ms, 8896 ns/exception

which... in the grand scheme of things: is pretty reasonable. I very much doubt that a different API here would have the effect you're after.

**Comment by SpiritBob** [comment]
I'm confused then why this [document](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance) by microsoft states that we should be wary of performance if we expect to throw a lot of exceptions?

Exact quote: 

> One common concern related to exceptions is that if exceptions are used for code that routinely fails, the performance of the implementation will be unacceptable. This is a valid concern.

Thank you for yet again reaching out for me @mgravell , you're the best! 😄

**Comment by mgravell** [comment]
A: "a lot" is contextual; relative to calling out-of-process and off-box, it is virtually impossible for exceptions to be the limiting factor

B: it is an inescapable ADO.NET feature that error messages in the data stream (with a high enough severity) **are raised as exceptions**. So if you're seeing it as an exception today, we can't *remove* the exception - all we would be doing would be catching it at a different point, and returning a different result to you. But it still had to be caught, because *is isn't us that throws it*

Does that make sense?

**Comment by SpiritBob** [comment]
I think it does.

I'm not sure what the terms "out-of-process" and "off-box" exactly mean, though I'm aware that ASP.NET Core applications can run in-process/out-of-process.

**Comment by mgravell** [comment]
By out-of-process and off-box I'm talking about the actual database; often, in systems where performance is a serious consideration, the database will be hosted by a dedicated RDBMS server, usually with a lot more CPU and memory than your web-server nodes (which are weaklings by comparison) - and even if you're hosting the database on the same machine: it will often be in a separate process. In either case: round-trip time will be measurably non-trivial, so the time taken for an exception becomes largely irrelevant.

You *can* host databases in-process, but that tends to be for very small-scale scenarios, in which case: this level of consideration probably isn't important.

**Comment by SpiritBob** [comment]
I see, thank you for taking the time to explain this to me!
