### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Dapper, Version=2.0.0.0

### ISSUE THREAD

**Issue by GZI98** [StackExchange/Dapper#1617]
I am using a Class Library, within I am trying to run Dapper queries. When the code is executed I get this error:

 `System.IO.FileNotFoundException: 'Could not load file or assembly 'Dapper, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.'`

How do I fix this?

**Comment by mrobert09** [comment]
I am having this same issue and I'm not sure the fix for it. Nothing I can find online seems to help. I am following along a C# tutorial but modifying it to fit my own project ideas: https://www.youtube.com/watch?v=wfWxdh-_k_4

When I get to connect Dapper to my project's form I get to the exact error GZI89 was having. For reference, I am on a basically fresh install of VS2022, this is the only project I've opened on this install, and this is the only NuGET package I've installed. Any help would be appreciated in fixing this issue.

**Comment by mrobert09** [comment]
I am having this same issue and I'm not sure the fix for it. Nothing I can find online seems to help. I am following along a C# tutorial but modifying it to fit my own project ideas: https://www.youtube.com/watch?v=wfWxdh-_k_4

When I get to connect Dapper to my project's form I get to the exact error GZI89 was having. For reference, I am on a basically fresh install of VS2022, this is the only project I've opened on this install, and this is the only NuGET package I've installed. Any help would be appreciated in fixing this issue.
