### ISSUE TITLE
PCL Support

### ISSUE THREAD

**Issue by kjeremy** [StackExchange/Dapper#265]
Is it possible to use dapper in a portable common library?  If not how much work is it?

**Comment by mgravell** [comment]
Not at the moment, since PCL doesn't support the meta-programming APIs that dapper exploits. This is also true of vNext (whatever they've renamed it to this week), so I hope that whatever we do for vNext also offers something for PCL. I definitely want it to work on vNext, since that has server-side elements (I'm mainly a server-side person).

**Comment by mgravell** [comment]
as for "how much work" - pretty much everything will need to be redone from scratch to work on PCL and (as I understand it currently) vNext. So it might be more "daughter of dapper" than "dapper"

**Comment by NickCraver** [comment]
Going to close this out as the situation hasn't changed. Several issues are tracking non-IL-gen approaches (which Marc is throwing some time at playing with generators) - if we add it, everyone will know :)
