### ISSUE TITLE
Dapper does not appear to expand objects properly with Oracle multi-column IN statements.

### ISSUE THREAD

**Issue by taylorkj** [StackExchange/Dapper#305]
Oracle supports multi-column IN statements, i.e., SELECT \* FROM table WHERE (col1, col2) IN (
(
(value1a, value2a), (value1b, value2b)
)
I received an error when providing Dapper with an array of objects to replace with the values for value1a and value1b, etc.  It appears it only handle arrays of primitive, i.e. simple types such as strings, integers, etc., not objects.  Please correct me if this is not the case.

Thank you, Ken Taylor kentaylor@ucdavis.edu

**Comment by NickCraver** [comment]
Since we don't have plans to add this to Dapper proper (it's Oracle specific), I recommend anyone seeking this ask for such a feature on the Dapper.Oracle library to see if they'd consider such a thing (and work with us on any generation plug points _if we must_ here): https://github.com/DIPSAS/Dapper.Oracle/
