### ISSUE TITLE
Enclosing column names in square brackets breaks Dapper.Contrib in PostgresSQL

### ISSUE THREAD

**Issue by oliverw** [StackExchange/Dapper#336]
Enclosing column names in square brackets completely breaks Dapper.Contrib in PostgresSQL.

<code>insert into products([Title], [ManufacturerId],) values((('Vibe P1')::text), ((1)::int4)) RETURNING Id</code>

**Comment by johandanforth** [comment]
@oliverw Could you please explain a bit more what you are trying to do. The dapper.contrib insert extension has been tested quite a lot I believe.

**Comment by oliverw** [comment]
Well, the queries above, and the one below have been generated by Dapper.Contrib (latest version from NuGet). When running the query below through NpgSql 3.0 (though happens on 2.x as well)  it results in the following error (sorry for the German error message, I have yet to figure out how to force the PGSQL error log to be in English):

<code>
2015-09-16 12:24:17 CEST	FEHLER	Syntaxfehler bei '[' bei Zeichen 30	
2015-09-16 12:24:17 CEST	ANWEISUNG	update rss_product_feeds set [Url] = $1, [Region] = $2, [Marketplace] = $3, [Name] = $4, [Created] = $5, [LastProcessed] = $6, [TimesProcessed] = $7 where [Id] = $8	
</code>

If I patch SqlMapperExtensions.cs to omit generating the square brackets, everything works as expected.

**Comment by NickCraver** [comment]
@oliverw sanity check here: I see an extra comma in your column list - you sure that's not a contributing factor here...or is that a mis-paste?

**Comment by AndrewSmart** [comment]
See [mrjoltcola's](http://stackoverflow.com/questions/19657101/what-is-the-difference-between-square-brackets-and-single-quotes-for-aliasing-in) explanation for a detailed understanding of this issue.

This square bracket issue causes Dapper.Contrib to not work with MySQL, and as oliverw noted, PostgresSQL.

As a solution, I suggest augmenting the [ISqlAdapter interface](https://github.com/StackExchange/dapper-dot-net/blob/bbf93cb260b10ca88ae036d74b2789a6fd72fb27/Dapper.Contrib/SqlMapperExtensions.cs#L628) with columnList and parameterList creation methods, such that the columns & values are quoted with appropriate delimiters for each SQL provider where appropriate.

**Comment by tms** [comment]
Just for history, #60 and #298 introduced the non-universal escaping. Something similar almost happened with `Dapper.Rainbow` in #167 too, but @mgravell reverted after I pointed out it broke compatibility. Whatever solution is decided on here should probably be applied to that code as well, since it currently doesn't allow escaping.

**Comment by johandanforth** [comment]
Thanks for the pointers @tms So double quote seems to be the right way of escaping column names on most database platforms but I'll spend some time today and dig into it. This must be solved.

**Comment by johandanforth** [comment]
Seems that the SQL-99 standard specifies that double quote (") is used to delimit identifiers, but at least MySQL has to be in ANSI mode and SQL Server only supports it when QUOTED_IDENTIFIER is ON. The contrib extensions for Insert, Update and Delete all use brackets, not just the Insert. So the question is, should we replace the brackets with double quotes everywhere and refer to the standard (and risk breaking working code out there)? Or perhaps add some other way for devs to supply a escape character, with a delegate or other method?

**Comment by Tewr** [comment]
Introducing delimiter of a specific dialect was probably a mistake, so forcing another, even if standard, would probably be a mistake as well. Specifying delimiters in the ISqlAdapter implementation as suggested by @AndrewSmart could be the way to go as brackets may be used in sql server regardless of the `QUOTED_IDENTIFIER` setting. Don't know about MySql ANSI mode though. I guess the ansi mode setting could be read (`SELECT @@SESSION.sql_mode;` ?) in a specific MySql ISqlAdapter adapter and eventually be cached on the connection instance. The impact of breaking working code may be somewhat limited as the current state of affairs seem to have broken some code already. Brackets would be the default as it is now (as SqlServerAdapter is default) and the other adapters could use double quote.

**Comment by AndrewSmart** [comment]
@Tewr In MySQL backticks as the identifier delimiter will [always work](http://dev.mysql.com/doc/refman/5.7/en/identifiers.html) regardless of its `ANSI_QUOTES` setting.

**Comment by johandanforth** [comment]
Yes @Tewr and @AndrewSmart , specifying delimiters in ISqlAdapter implementations feels right to me too. The sql server adapter could keep using brackets as you wrote. Not sure at all about the proper way to handle mysql, but from what I can google, http://dev.mysql.com/doc/refman/5.6/en/identifiers.html says a "backtick" should be used. And for sqllite and postgressql use double quotes. How bout that?

I'll take a look at how to implement this in all parts needed, Insert(), Update() and Delete() and there corresponding async methods.

**Comment by tms** [comment]
@johandanforth Agreed, that seems like the right approach. I was going to go ahead and implement something yesterday, but I wanted to confirm first with you, @NickCraver, and @mgravell there was no concerns with changing that interface. If you have the free time though I'll defer to you :)

**Comment by AndrewSmart** [comment]
@johandanforth Sounds good to me. Though thinking back to what @tms said in #167, I think it would be optimal to not escape every identifier in pursuit of Dapper's maximal performance goal. I'd suggest to have users either not use reserved keywords, or use another data annotation such as [Table("Tablename", EscapeIdentifiers=true)]. That data annotation could drive the escaping as implemented in ISqlAdapter implementations.

**Comment by johandanforth** [comment]
@AndrewSmart hmmm, yeah, it will impact performance. Not much, but still. I tend to agree with you, but if the default would be to *not* escape names, that would affect some existing code out there which depend on the existing brackets around column names.

**Comment by tms** [comment]
The difference is probably negligible anyway, since there's already string concatenation being done to build the queries. Could determine which types have parameters needing escaping the first time they're encountered and cache the result, but that seems like it's probably overkill.

On the flip side, if it actually is an issue I'm sure someone will complain about it after the implementation is in place, so assuming no one proactively profiles it, it can always be handled when it comes up.

**Comment by AndrewSmart** [comment]
@tms Well, the string concatenation would be pertinent to Dapper itself, but their are also performance effects in the SQL engine such as logging. On a large project in the past w/ MySQL I did see a useful performance benefit after taking universal quoting out (millions of inserts, hundreds of columns). Though then I was naive and not using prepared statements... That's what struck up my thought :) But you're right too about the flip-side. So thank you for working on this!

**Comment by johandanforth** [comment]
PR #352 now also contains fixes for this issue

**Comment by rusio** [comment]
We would greatly appreciate a release of Dapper.Contrib with the fix.

**Comment by rusio** [comment]
Is there a chance that Dapper.Contrib is released on NuGet in the near future?
This is a blocker for anyone using Dapper.Contrib with PostgreSQL.

**Comment by hoquangthaiholy** [comment]
I have same ploblem on MySQL. Please update package on Nuget. Thanks

**Comment by hoquangthaiholy** [comment]
I compiled from latest code for who want to use right now. Download this image and rename extension to zip. (Because, Github did't support upload zip file)
![dapper contrib 1 44](https://cloud.githubusercontent.com/assets/614264/11168164/9d1e834c-8bb6-11e5-92ab-7228cb34bca4.png)

**Comment by johandanforth** [comment]
The Dapper.Contrib Nuget package is now updated to version 1.44. Sorry for taking so long.
https://www.nuget.org/packages/Dapper.Contrib/1.44.0
/cc @hoquangthaiholy @rusio

**Comment by oliverw** [comment]
@johandanforth Thanks for updating the package. Unfortunately this update contains a new breaking change. Column names are now always enclosed in double quotes which implies that all of your column names represent a **case-sensitive** match to the property names of your POCO Entitities.

Without quoting PostgreSQL converts all column-names to lowercase which would be the desired behavior.

Please provide the possibility to opt-out of column-name quoting or at the very least make `ISqlAdapter.AppendColumnName` and `ISqlAdapter.AppendColumnNameEqualsValue` virtual.

**Comment by NickCraver** [comment]
@oliverw I understand *not* quoting leading to more issues. If you had any other characters in there you'd break for *other* reasons, like spaces, dots, etc. 

Is there a middle ground that solves both that we're unaware of? The mapper is case-insensitive by default so we'd want to handle not-breaking and case-insensitive if possible. I'm unaware of a syntax is Postgres that does this, though.

**Comment by shrayasr** [comment]
Guys, is there any progress on this? We're writing a sufficiently big system on ASP NET Core which uses Dapper.Contrib heavily and this is becoming quite a concern. Without this solved, we're forced to either 

1. Keep our DB column names in camelCase - Which is ugly.
2. Keep our Entities in lowercase - Which is also ugly. 

:disappointed: 

cc @NickCraver @johandanforth

**Comment by shrayasr** [comment]
As @oliverw pointed out, it would be nice to have quoting as opt-in or for certain columns. For now, we've forked Dapper.Contrib and made the following changes (not public): 

- Disable quoting by default
- Introduce a `Quote` attribute that will enable quoting on chosen fields in entities. Eg:
    
        public class Book
        {
          public int Id { get; set; }
          public string Isbn { get; set; }
          [Quote("number")]
          public string Number { get; set; }
        }

  this would generate the following SQL statement: 

        INSERT INTO BOOK (id, isbn, "number") ...

It would be nice if we could get a discussion started on it. I assume that we're not the only ones affected by this. Since the release on NuGet wraps both release of the `[ExplicitKey]` (a beautiful feature) and Quoting, We aren't able to pick only the version where only `[ExplicitKey]` is implemented but ignore the Quoting.

Looking forward to your comments.

**Comment by johandanforth** [comment]
@shrayasr sorry for not answering earlier. I understand your problem. What if a `[Column]` attribute (from `DataAnnotations`) could be used? If Contrib found such an attribute on a property, the name of the attribute could be used explicitly, and nothing is escaped/quoted. This is the other way around from what you suggest, but it should not break old code. Just brainstorming here...

We could also include our own `[Column]` attribute like we do for `[Table]` and  `[Key]`.

/cc @hoquangthaiholy @rusio @oliverw

**Comment by shrayasr** [comment]
> sorry for not answering earlier. 

No problem at all :+1:

> I understand your problem. What if a [Column] attribute (from DataAnnotations) could be used? 

I'm sorry, but I'm not sure which `DataAnnotations` you're referring to?

> If Contrib found such an attribute on a property, the name of the attribute could be used explicitly, and nothing is escaped/quoted. 

If i'm understanding this correctly, what you mean is: 

- Quote by default,
- Unquote when a `[column("foo")]` is encountered and use `foo` instead of whatever the field name is.

So something like 

```C#
class Employee 
{
  public int Id { get; set; }
  public string Name { get; set; }
}
```

would generate the column string as

```SQL
"Id", "Name"
```

and

```C#
class Employee 
{
  public int Id { get; set; }
  [Column("foo")]
  public string Name { get; set; }
}
```

would generate the column string as

```SQL
"Id", foo
```

Right?

[...]

> but it should not break old code. Just brainstorming here...

Could you elaborate on breaking older code? Are you saying that not quoting by default will break older code? 

> We could also include our own [Column] attribute like we do for [Table] and [Key].

+1 to this. This is kind of what we've currently done with the `[Quote]` attribute. But does this bring with it more maintainability issues? If we introduce optional quoting, we'll have a bunch  of `if-else` conditions looming in the `AppendColumnName` and the `AppendColumnNameEqualsValue` functions.

If you like, I can share our version of the `[Quote]` attribute. Fair warning: The implementation is **majorly** hacky :wink:

**Comment by shrayasr** [comment]
@johandanforth gentle reminder :bell:

**Comment by EliotJones** [comment]
I feel I'm probably missing the obvious fix but I can't get Dapper.Contrib (1.50.0 .NET Core) working with PostgreSQL (9.6.1) because it automatically wraps the property names in the ```"``` double quote which makes the query case sensitive.

Since my properties have standard C# naming (i.e. upper-case) and I don't want to create upper cased column names in PostgreSQL, is there any annotation to make the properties map lower case, or omit the quotations in the generated SQL altogether?

**Comment by shrayasr** [comment]
@EliotJones We also had the same problem and because of this, we forked Dapper.Contrib and rewrote the implementation where they aren't quoted by default for PG

On a related note, looks like there's an open PR here: #512 that allows us to plug in our own Custom Adapters and override just the functions we need to do the job.

**Comment by rusio** [comment]
Besides a default mapping, a [Column] attribute for explicitly naming a database column would be great. In fact it is strange, that currently there is no way to have diverging names of C# properties and database columns. 

It is a valid use case when you have c_style_database_columns, but want CSharpStyleProperties. Or if you want to be able to rename the C# property (without breaking the mapping to the database schema), because the naming in the database is so bad, that it makes your C# code unreadable.

Currently I am working this around by using C# properties which are named like ugly_c_style_database_columns.

**Comment by shrayasr** [comment]
I agree with @rusio. It was because of this that we decided to name our columns `withoutanyseparators`. While it does the job, I would **prefer** to see my columns `with_an_underscore_separator`. 

Our fork works around this by exposing a `Quote` attribute to handle both optional quoting and different column names. (ref: https://github.com/StackExchange/dapper-dot-net/issues/336#issuecomment-181304021)

**Comment by EliotJones** [comment]
Thanks @shrayasr and @rusio. I will possibly also create a fork since I may also want to introduce the concept of "read only" columns (xmin for postgres). I'd plan on changing or inheriting from the ```Table``` annotation to include ```PostGresTable(Name, IsQuoted = bool)``` for example but I can also see the benefit of having a ```Column``` attribute. However maybe it's trying to move too far away from Dapper.Contrib's small footprint.

**Comment by NickCraver** [comment]
I've introduced a new proposal for V2 here, can you all please take a look and chime in with thoughts? The proposal is in #722 - consolidating discussions there to solve this *everywhere* in V2.

**Comment by timematcher** [comment]
Is there a workaround to tell Dapper not to quote columns? I am also using postgres and try to get it work. I have hundred of tables and corresponding thousands of columns and putting the **Column** attribute would take a lot of effort and time. 

Is there a global switch that can be used to disable quoting for columns?
