### ISSUE TITLE
Automatic multi mapping : would this be possible ?

### ISSUE THREAD

**Issue by christopheblin** [StackExchange/Dapper#350]
At the moment, you have to write something like :

``` C#
var sql = @"select * from #Posts p 
left join #Users u on u.Id = p.OwnerId 
Order by p.Id";

var data = connection.Query<Post, User, Post>(sql, (post, user) => { post.Owner = user; return post;});
var post = data.First();
```

Would it be possible to support something like :

``` C#
var sql = @"select p.id, p.title, p.content, u.Id as owner__id, u.Name as owner__Name
from Posts p 
left join Users u on u.Id = p.OwnerId 
Order by p.Id";

var data = connection.Query<Post>(sql);
var post = data.First();
```

As you can see double underscore would be understood as "nested object" and I do not have to specify the "strange" function.

**Comment by phnx47** [comment]
Hi @christopheblin! I writing my lib: https://github.com/phnx47/MicroOrm.Dapper.Repositories

I just finished add join's queries. 

Exemple:

```
using (var conn = new SqlConnection(connetionString))
           {
                var rolesRepository = new RolesRepository(conn);
                var roles = await  rolesRepository.FindAllAsync<User>(x => x.Users);
            }
```

Maybe it help for you?

**Comment by christopheblin** [comment]
@phnx47 : I do not think it will help since most of my queries are not crud (i.e I joins multiple tables but I do not take all the columns during the join)

My point is that MultiMap is really the kind of thing I want to do, I just find the syntax difficult to use and to read afterward.

**Comment by phnx47** [comment]
@christopheblin You can write extensions based on my code. I use attributes and generic methods, and I choose what I need to join.

**Comment by NickCraver** [comment]
Aside from the "Id" default key column, nothing in Dapper is convention based. I'd be very hesitant to introduce it here, partly because IMO, the proposed syntax isn't intuitive (I don't think it'd help if it were, to be fair). For example, what if I had `owner` and `Owner`? What if I had a `owner__id` property? There's a lot of magic in convention-based behaviors like this that usually becomes not-awesome in a lot of situations.

**Comment by christopheblin** [comment]
I take a look on the Internet and it seems like fluentdata is doing it with a single underscore. I agree that convention based may be not awesome in some cases but here I think this is truly useful. Also, the separator could be configurable like the split on option and I think that a single underscore is not enough as it is common to find it in a property which is more unlikely for two underscores

**Comment by NickCraver** [comment]
Barring additional reasons, I'll close this one out in a few days because I just don't think we want to go this route - it's convention based and therefore will always be "magical". More importantly it's a breaking change *to text*, a query that works fine will give no compilation warnings, but queries with underscores will just stop mapping correctly. It would also mean Dapper is hooking up the reference `.Owner` in your example which can have side-effects in itself. Today, this may not be intended. It also means `Select *` is out the door, since *every* new property has to be maintained in every SQL query you want to map in this way - that dramatically lowers the usefulness.

I think there are ways to make it *less* magical and more intent oriented like `AS [Prop.Prop]` but then we're talking about far more query work than the mapping itself. The intent of Dapper is to be slim, fast, and as many features *as is reasonable* while respecting the principle of least surprise. When you look at the savings here, we're really only talking about 1 character in the top example, and that evaporates with property #3 switching into a higher cost.

I really do appreciate the thoughts on the issue, I just don't think this one is a good fit for Dapper. All that being said, I've seen a few issues where making the mapper generation a bit more pluggable would be beneficial, and it'd allow you to do something like this is you *really* wanted, without affecting default behavior. I'm not sure how practical that is given that we generate it at a low level, but we're going to take a look.

**Comment by christopheblin** [comment]
I really appreciate the thoughts you give to my idea. I hope to see the plug in mechanism soon :)
