### ISSUE TITLE
Serializing DapperRow

### ISSUE THREAD

**Issue by BHare1985** [StackExchange/Dapper#354]
I stored SQL results into a dynamic List, of which has an underlying DapperRow type. I am trying to serialize/unserialize this List of which XMLserializer complains:

There was an error generating the XML document. ---> System.InvalidOperationException: To be XML serializable, types which inherit from IEnumerable must have an implementation of Add(System.Object) at all levels of their inheritance hierarchy. Dapper.SqlMapper+DapperRow does not implement Add(System.Object).

Is there a way around this (besides the obvious casting the results to my own concrete object), or is it possible to somehow make DapperRow objects conform to System.Xml.XMLserializer constraints?

**Comment by mgravell** [comment]
This is an interesting question. While it is *usually preferable* to load
the data into a custom type and serialize that, I totally "get" that this
isn't always possible, and this becomes especially relevant since CoreCLR
doesn't have DataTable. I will need to investigate what is possible here -
it does seem a desirable feature. It should be possible to do this via
IXmlSerializable, but deserialization may be especially problematic since
we don't normally expose the container that bundles the rows and holds the
shared schema. That may involve some changes. Definitely worth the thought
time, but it isn't a tiny thing.

**Comment by NickCraver** [comment]
TODO: Revisit with `netstandard2.0`.

**Comment by NickCraver** [comment]
Given the rarity of the request and the weight additions to DapperRow would involve (if it adds any state), going to close this out as something we don't currently intend to add support for.
