### ISSUE TITLE
Accept lambda for single-table SELECT

### ISSUE THREAD

**Issue by burnchar** [StackExchange/Dapper#438]
Request:

I believe a `Query<T>` prototype which accepts a lambda when querying a single table would be useful. Currently, only multi-mapping prototypes allow this.
Use case:

``` C#
connection.Query<TableMeta, TableMeta>(tableMetaSql, (t) =>
{
    t.InsertSql = GenerateSomeSql(t.Schema, t.TableName);
    return t;
}, new { param1, param2});
```

In the above situation, data (from database A) contains some fields that must be populated application-side before inserting into database B.
It feels somewhat inelegant perhaps calling an outside method to modify queried data, but I feel it's more elegant than later foreach()ing through the data and manually making such a change.

**Comment by NickCraver** [comment]
IMO, this would be a bit superfluous on the API side since the alternative is (IMO) much clearer and the same number of lines:

```C#
var items = connection.Query<TableMeta, TableMeta>(tableMetaSql, new { param1, param2});
foreach(var t in items)
{
    t.InsertSql = GenerateSomeSql(t.Schema, t.TableName);
}
```
This also prevents several capture rules from coming into play on the performance side.

**Comment by NickCraver** [comment]
@burnchar any additional thoughts here?

**Comment by burnchar** [comment]
@NickCraver I am coming from "I can do row-level processing when joining tables. Why am I forced to join tables to do this? Why not add a new prototype since the functionality is there?" 
Your position seems to be, "Why add unnecessary code to Dapper when requiring an outside loop (or whatever) is probably clearer?"
A fair point; unnecessary complexity is the developer's bête noire, but so is inconsistency and artificial limitation.
Ostensibly the lambda prototypes are to help joins, but I can think of many other situations where they are useful:
- Custom joins (when SplitOn is insufficient)
- Composite primary key logic
- Processing or joining rows when the column names are not known ahead of time (A problem I am working on now)
- Avoid creating intermediary objects 
- Avoid looping over the same data structure twice

**Comment by NickCraver** [comment]
@burnchar I think you misunderstand the point of the (appropriately named) `map` function, it is quite simply there to map pieces together - not for general processing. There are many reasons *not* do do anything complex there, the least of which is leaving your database connection open for long periods of time for a client side operation. This increases the duration of locks, increases the chances of escalation and other downstream issues. It's actively bad practice for us to encourage such things.

The `map` right now *has* to exist, because we're returning one `List<TReturn>` and don't know how to do that unless you specify it. It's a necessity.

To address each point:

> Custom joins (when SplitOn is insufficient)

How is this not multi-map already? A `foreach` still works there.

> Composite primary key logic

Can you provide examples? It's still just an object in our world. If the key is very important it should likely be ingrained on the object or you're unlikely to find the `List<T>` result set to which you're constrained to be useful.

> Processing or joining rows when the column names are not known ahead of time (A problem I am working on now)

What is your scenario then, `dyanmic`? I don't see wins there over a `foreach`, if you have some: examples please.

> Avoid creating intermediary objects

How does the `foreach` create extra objects? You're still iterating on the same list.

> Avoid looping over the same data structure twice

I'm not really concerned with looping over the data structure twice, given that you can `buffered: false` and IEnumerable, that's also avoidable. You'd just `foreach` over the result and do as you please. For "small" (let's say under a million rows), looping over the data is generally the least of the costs in play. Only memory buffering is a real point there, but that's addresses by the non-buffered option and a proper data flow in general.

**Comment by burnchar** [comment]
There seems to be some pretty strong resistance to the suggestion, and I'm glad -- developers which lack strong, reasonable filters for new feature requests end up with a complicated mess.

You are absolutely correct that most/all of the cases I listed can be handled with a `foreach`, but then, so can the multi-mapping feature, so why have it at all?
For convenience, for quicker implementation, for code that does what it needs to to return the desired object in one step. I feel this applies still when the data returned is not as it is in Dapper's examples, and that adding a map prototype is a reasonable solution.

As for performance and keeping the connection open, I think this is the developer's choice. Most basic processing of rows is unlikely to add a significant amount of time to the connection's duration, similar to what has already been stated about the minor overhead of looping over a data structure twice and similar to the mapping that `map` is intended for. It is of course possible to call `sleep(1000)` within a new map prototype, but it is also possible for table join situations in Dapper today. The new prototype merely makes Dapper consistent.

My unknown column names situation does indeed use a dynamic read as `IDictionary<string, object>`. Handling M:M joins does currently have to us a for loop. Because an in-Dapper mapping of rows is possible when the column names are known, when using multi-mapping, it seem natural to me to allow such a thing for dynamics as well. I know that Dapper supports <Dynamic> only reluctantly (which is as I would do, since usually you know at compile time the details of the tables), so I can't expect first-class citizen support for all uses of dynamic.

I don't know that this is a batter worth fighting, because it is not a big deal to write a `foreach` loop and I respect efforts to keep my favorite libraries lean'n'mean. If such an addition still sounds like a bad idea, please say so and I'll close the request without resistance.

**Comment by NickCraver** [comment]
Sorry I never followed up here. Confirming this just doesn't seem like an addition for the core library. We already have a ton of overloads here and this one's easily support as-is, with more efficient code as well.

**Comment by NickCraver** [comment]
Going to close this out, I appreciate the back and forth here :)
