### ISSUE TITLE
Blocking method called in async method

### ISSUE THREAD

**Issue by cremor** [StackExchange/Dapper#535]
I've noticed that the methods SqlServerAdapter.InsertAsync and SQLiteAdapter.InsertAsync call the blocking method GridReader.Read although there is a ReadAsync method available.

I suggest to use the AsyncFixer [Visual Studio extension](https://visualstudiogallery.msdn.microsoft.com/03448836-db42-46b3-a5c7-5fc5d36a8308) or [NuGet package](https://www.nuget.org/packages/AsyncFixer) to analyze the whole solution for async usage problems (not my work, but I found it useful).

**Comment by NickCraver** [comment]
Confirmed this is an issue, but it goes deeper, these need a refactor for RETURNING and such anyway where appropriate. There are very bad assumptions in play here, such as the PK being an `int` at all.
I'll look at this as a whole with some new methods (e.g. `Insert<T>` where `T` : PK type).

**Comment by SpaceOgre** [comment]
Not sure if this is the wrong place but it felt wrong to start a new issue since this seems to be the problem I'm having atm.

When using InsertAsync the program just hangs forever waiting for a response, if I on the other hand use Insert it works as it should. Should I take this issue as a "Stay away from InsertAsync until this issue is fixed?"
