### ISSUE TITLE
Positional Parameters

### ISSUE THREAD

**Issue by ghjlark** [StackExchange/Dapper#560]
https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper/SqlMapper.cs#L1624

Why is this an exception? Is there a different way to reference a parameter multiple times in a query (ODBC)?

**Comment by mgravell** [comment]
It is an exception to prevent people accidentally passing large values
multiple times. Options:

- store the parameter into a variable and use it from there
- use different variables to signify that you are intentionally using the
same value multiple times

It might also perhaps be appropriate to make this an *option* that you can
disable.
On 14 Jul 2016 9:53 pm, "ghjlark" <notifications@github.com> wrote:

https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper/SqlMapper.cs#L1624

Why is this an exception? Is there a different way to reference a parameter
multiple times in a query?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/dapper-dot-net/issues/560>, or mute the
thread
<https://github.com/notifications/unsubscribe/AABDsIZ7WRGyh_HDzryVp9MjzhlOQ8oMks5qVqHWgaJpZM4JM1v2>
.

**Comment by ghjlark** [comment]
Understandable. I'm passing an object and letting Dapper map the variables for me, I'm not explicitly defining dynamic variables. For now I can change that and create redundant variables, but it would be nice if this wasn't an exception.

**Comment by NickCraver** [comment]
Since we haven't received another request for this - closing out in favor of current behavior.
