### ISSUE TITLE
Update README to show performance comparison of Dapper vs. EF Core

### ISSUE THREAD

**Issue by kevinrood** [StackExchange/Dapper#562]
In the table comparing performance of Dapper to other data access libraries, it would be fantastic to see an entry for EF Core.

**Comment by kbugala** [comment]
I agree, it would be great to see how Dapper compares to the EF Core.

**Comment by riyasat** [comment]
![dapperbenchmark](https://cloud.githubusercontent.com/assets/5029964/17739153/72008c8e-6494-11e6-9d0f-cf10659a9b13.JPG)

Here are a simple test benchmark for both of the awesome ORMs. Dapper is winner because it's making simple query to DB (as an old days) but entity framework is making query based on linq.

**Comment by vdaron** [comment]
Could you give the code as well ?

**Comment by riyasat** [comment]
Sure,

I removed few properties from Organization model for simplycity. You can add more properties if you want to make it more complex

[DapperTest.zip](https://github.com/StackExchange/dapper-dot-net/files/425036/DapperTest.zip)

Happy Codding.

**Comment by NickCraver** [comment]
I've just completed updating the benchmarks (and README) to current (including EF Core). If anyone sees issues with the benchmarks please let me know or even start with a PR and we'll get them fixed up and re-run :)
