### ISSUE TITLE
Is there a Dapper.Rainbow release for .NET Core?

### ISSUE THREAD

**Issue by zkohl** [StackExchange/Dapper#676]
It would be great if we could get Dapper.Rainbow for .NET Core. The Nuget package for Dapper.Rainbow seems to be incompatible.

**Comment by NickCraver** [comment]
I'll take a look for v2, haven't look at this code in ages.

**Comment by martinsteel** [comment]
@zkohl if you're in a hurry the current master builds on .NET Core and works fine with Dapper from NuGet. Not quite as convenient as you'll have to package yourself or bring the source in to your solution but it lets you get up and running.

**Comment by NickCraver** [comment]
There is now a build for `netstandard1.3` up on MyGet: https://www.myget.org/feed/stackoverflow/package/nuget/Dapper.Rainbow If anyone wants to give it a go, I'd really appreciate the testing.

We don't have tests for Rainbow because it's so old, nor the time to add them...if the community wants to contribute we'd happily take them.

**Comment by NickCraver** [comment]
This is up on NuGet, closing it out!
