### ISSUE TITLE
ExecuteScalar Method Not Found Exception

### ISSUE THREAD

**Issue by zerosnap** [StackExchange/Dapper#684]
I cannot for the life of me get ExecuteScalar working with a Scalar Function.  I've looked around, but haven't found much help.  This is the function we are calling in Dapper vs 1.502

```C#
var result = await WithConnection(c => Task.Run(() => c.ExecuteScalar<decimal>(
     //@"SELECT [dbo].[sp_GetTotalPVForLifeOfDistributor] (@distributorId)",
     "[dbo].[sp_GetTotalPVForLifeOfDistributor]",
     //@"DECLARE	@return_value decimal
     //EXEC	@return_value = [dbo].[sp_GetTotalPVForLifeOfDistributor]
      //		@DistributorId = 1001
     //		SELECT	'LifetimePv' = @return_value",
     //new {distributorId})));
     new { DistributorId = distributorId })));
```
I would think just calling it with "[dbo].[sp_GetTotalPVForLifeOfDistributor]" would do the trick, like you'd do when calling a CommandType.StoredProcedure...  All the commented out code is just different attempts I've made at making this work.  Is this a syntax issue or am I missing something entirely?  Here is the error I receive every time. 

> Method not found: 
```
!!0 Dapper.SqlMapper.ExecuteScalar(System.Data.IDbConnection, System.String, System.Object, System.Data.IDbTransaction, System.Nullable`1<Int32>, System.Nullable`1<System.Data.CommandType>)'.
   at Senegence.Orders.Core.Repositories.OrderRepository.<>c__DisplayClass27_0.<GetLifetimePv>b__1()
```

**Comment by mgravell** [comment]
there's a lot going on there - tasks, async, SPs, etc; you mention a scalar
function but I can't see any use of that in the code...

Do you have a minimal example that shows what you're trying to do without
the ancillary bits? I can knock an example together, of course, but it
might not actually be what you meant...

On 24 Jan 2017 5:28 p.m., "Nathan Gallenson" <notifications@github.com>
wrote:

I cannot for the life of me get ExecuteScalar working with a Scalar
Function. I've looked around, but haven't found much help. This is the
function we are calling.

var result = await WithConnection(c => Task.Run(() =>
c.ExecuteScalar<decimal>( //@"SELECT [dbo].[sp_
GetTotalPVForLifeOfDistributor] (@distributorId)", "[dbo].[sp_
GetTotalPVForLifeOfDistributor]", //@"DECLARE @return_value decimal //EXEC
@return_value = [dbo].[sp_GetTotalPVForLifeOfDistributor] // @DistributorId
= 1001 // SELECT 'LifetimePv' = @return_value", //new {distributorId})));
new { DistributorId = distributorId })));

All the commented out code is just different attempts I've made at making
this work. Is this a syntax issue or am I missing something entirely? Here
is the error I receive every time.

Method not found: '!!0
Dapper.SqlMapper.ExecuteScalar(System.Data.IDbConnection,
System.String, System.Object, System.Data.IDbTransaction,
System.Nullable1<Int32>,
System.Nullable1<System.Data.CommandType>)'.
at Senegence.Orders.Core.Repositories.OrderRepository.<
>c__DisplayClass27_0.b__1()

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/dapper-dot-net/issues/684>, or mute the
thread

**Comment by zerosnap** [comment]
It didn't format very well, did it? The scalar function I'm trying to execute is called "[dbo].[sp_GetTotalPVForLifeOfDistributor]"  It takes in an int parameter of @DistributorId and outputs a decimal.  Any help would be much appreciated.  Let me know if there's more you need, please.  Thanks!

**Comment by NickCraver** [comment]
The error seems to indicate Dapper isn't being deployed correctly, are you sure it's ending up in our output directory? e.g. is the DLL missing?

I also second the questioning of Task here, you likely want something like this:
```c#
var result = await WithConnection(c.ExecuteScalarAsync<decimal>(
  "[dbo].[sp_GetTotalPVForLifeOfDistributor]", new { DistributorId = distributorId }));
```
Though be aware Dapper will open (and close) the connection for you if needed...so you can do something as simple as:
```c#
var c = GetConnection();
var result = await c.ExecuteScalarAsync<decimal>(
  "[dbo].[sp_GetTotalPVForLifeOfDistributor]", new { DistributorId = distributorId });
```

**Comment by mgravell** [comment]
I could be wrong, but I think you'll also need a "select" to query a
function.

**Comment by NickCraver** [comment]
No info to go on here - closing out to cleanup.
