### ISSUE TITLE
Expose buffered parameter for Execute

### ISSUE THREAD

**Issue by mjeson** [StackExchange/Dapper#724]
Summary:

It would be really helpful to expose buffered parameter in Execute method, similar to Query method.

In SqlMapper.cs line 467, the Execute method always set to CommandFlags.Buffered

```c#
public static int Execute(this IDbConnection cnn, string sql, object param = null, IDbTransaction transaction = null, int? commandTimeout = null, CommandType? commandType = null)
{
    var command = new CommandDefinition(sql, param, transaction, commandTimeout, commandType, CommandFlags.Buffered);
    return ExecuteImpl(cnn, ref command);
}
```
This buffer feature is currently causing intermittent error on the following use case:

```c#
    DynamicParameter dapperParams = new DynamicParameter();
    dapperParams.Add("Return", null, DbType.Int32, ParameterDirection.ReturnValue, null);
    
    int rowAffected = conn.Execute("pr_ActiveSessions_CheckAndRenew", dapperParams.DynamicParameters);
    
    //Dapper error: Attempting to cast a DBNull to a non nullable type! Note that out/return parameters will not have updated values until the data stream completes (after the 'foreach' for Query(..., buffered: false), or after the GridReader has been disposed for QueryMultiple)
    //Dapper is by default buffering the parameters, which would not work for this CheckAndRenew
    int returnValue = dapperParams.Get<int>("Return"); //error here
```

**Comment by martygriffin** [comment]
+1

**Comment by mgravell** [comment]
the buffered parameter *doesn't apply* here. What this controls is whether
a data-reader is left open and consumed on-the-fly, vs being consumed in
advance and a list returned. With Execute, there **is** no data reader - it
uses ExecuteNonQuery.

So whatever the issue is, it has nothing to do with "buffered". Any example
code of when this (occasionally) happens?

**Comment by mjeson** [comment]
Error message:
Attempting to cast a DBNull to a non nullable type! Note that out/return parameters will not have updated values until the data stream completes (after the 'foreach' for Query(..., buffered: false), or after the GridReader has been disposed for QueryMultiple)

By this code:
C#
    ```
DynamicParameter dapperParams = new DynamicParameter();
    dapperParams.Add("Return", null, DbType.Int32, ParameterDirection.ReturnValue, null);
    
    int rowAffected = conn.Execute("pr_ActiveSessions_CheckAndRenew", dapperParams.DynamicParameters);
    
    int returnValue = dapperParams.Get<int>("Return"); //occassional error here. Get operation sometimes returns DBNull despite stored procedure below always returns either -1 or 0.
```

T-SQL
```
CREATE PROCEDURE dbo.pr_ActiveSessions_CheckAndRenew
    @SessionGuid     UNIQUEIDENTIFIER,
    @Token           VARCHAR(400),
    @TimeoutSeconds  INT
AS
    UPDATE dbo.ActiveSessions
    SET ExpireDt = DATEADD(SECOND, @TimeoutSeconds, GETDATE())
    WHERE SessionGuid = @SessionGuid
    AND Token = @Token
    AND ExpireDt > GETDATE();

    IF (@@ROWCOUNT = 0)
        RETURN -1;

    RETURN 0;
GO
```
I believe if SqlMapper.cs allows Execute to have CommandFlags.Unbuffered, it would solve this DBNull problem. This behavior does not occur when I use straight ADO calls.

**Comment by mgravell** [comment]
> I believe if SqlMapper.cs allows Execute to have CommandFlags.Unbuffered, it would solve this DBNull problem. 

That simply isn't the case; the thing that "buffered" does ***simply doesn't exist*** in the `Execute` scenario - there would be nothing the code could *do* with it. What we actually want is a "makeItWork" parameter - but for that to work we need to know why it isn't working. Obviously  this *might* have happened if there was an `IF` path in the TSQL that didn't set a `RETURN` value, but you clearly have that. My next thought would be some kind of exception, but I'd expect that to manifest differently. We need to figure out what is happening. I'll try to set up a scenario tonight that does something similar to your code here (or: exactly your code here), and call it a few million times in a row - see if I can get it to error.

**Comment by mjeson** [comment]
Its probably also because I call the Get before closing the connection. There are multiple asynchronous calls calling this section of code. ADO.NET allows it though, and does not return null at all for this case.

**Comment by NickCraver** [comment]
I'm not seeing an output parameter in your stored procedure, I'd expect to see a `@Return int OUTPUT`, for which you're setting the value. Currently that's not there...so the null appears correct. Am I missing something there? Return itself is not a magic parameter name, either you're observing the result or not...but the approach needs to line up on the DB side.

**Comment by mjeson** [comment]
@NickCraver its a return value, not an output parameter

**Comment by NickCraver** [comment]
@mjeson Yes, I understand the SQL...but you're accessing it as an output parameter, which doesn't exist and is therefore null, here:
```c#
dapperParams.Add("Return", null, DbType.Int32, ParameterDirection.ReturnValue, null);
```
...there's no actual `@Return int OUTPUT` that goes with that, and "Return" isn't some magical string value...it's literally the name of a parameter (which doesn't exist). Does that make sense?

Your C# code expects this:
```sql
CREATE PROCEDURE dbo.pr_ActiveSessions_CheckAndRenew
    @SessionGuid     UNIQUEIDENTIFIER,
    @Token           VARCHAR(400),
    @TimeoutSeconds  INT,
    @Return          INT OUTPUT
AS
    UPDATE dbo.ActiveSessions
    SET ExpireDt = DATEADD(SECOND, @TimeoutSeconds, GETDATE())
    WHERE SessionGuid = @SessionGuid
    AND Token = @Token
    AND ExpireDt > GETDATE();

    IF (@@ROWCOUNT = 0)
        SET @Return = -1;

    SET @Return = 0;
GO
```

**Comment by mgravell** [comment]
@Nick that is what .ReturnValue does - looks ok to me at first glance

On 15 Mar 2017 7:20 p.m., "Nick Craver" <notifications@github.com> wrote:

@mjeson <https://github.com/mjeson> Yes, I understand the SQL...but you're
accessing it as an output parameter, which doesn't exist and is therefore
null, here:

dapperParams.Add("Return", null, DbType.Int32,
ParameterDirection.ReturnValue, null);

...there's no actual @Return int OUTPUT that goes with that, and "Return"
isn't some magical string value...it's literally the name of a parameter
(which doesn't exist). Does that make sense?

Your C# code expects this:

CREATE PROCEDURE dbo.pr_ActiveSessions_CheckAndRenew
    @SessionGuid     UNIQUEIDENTIFIER,
    @Token           VARCHAR(400
),
    @TimeoutSeconds  INT,
    @Return          INT OUTPUT
AS
    UPDATE dbo.ActiveSessions
    SET ExpireDt = DATEADD(SECOND, @TimeoutSeconds, GETDATE())
    WHERE SessionGuid = @SessionGuid
    AND Token = @Token
    AND ExpireDt > GETDATE();

    IF (@@ROWCOUNT = 0
)
        SET @Return = -1;

    SET @Return = 0;
GO

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/724#issuecomment-286851093>,
or mute the thread

**Comment by NickCraver** [comment]
@mgravell aye, I read it wrong on first pass, because I've never see without the parameter prefix there...I'm not sure if it matters or not. Unsure what SQL does or doesn't do with the `@` prefix in the return context. Without the `@` in really old versions, it'd fall back to looking for an actual parameter, not the return type (how I read it here). The command type isn't set to stored procedure and I see `DynamicParameter` in the C# code above, not `DynamicParameters` which exist in Dapper, and I'm not sure what `dapperParams.DynamicParameters` is. My first glance is very confused, are we looking at an old lib here?

@mjeson What code are we looking at, and which version of Dapper are you on?

**Comment by mgravell** [comment]
@NickCraver I think you've hit the nail on the head with the stored procedure thing. Without that, this is an implicit EXEC without a RETURN.


Please add CommandType.StoredProcedure in the optional parameter.

**Comment by mjeson** [comment]
@NickCraver I am using Dapper.1.50.2. What do you suggest to capture the return value of a stored procedure ?

@mgravell I am using CommandType.StoredProcedure. I have defaulted the conn.Execute to the following:

```
        int Execute(
            string sql,
            object param = null,
            IDbTransaction transaction = null,
            int? commandTimeout = default(int?),
            CommandType? commandType = CommandType.StoredProcedure);
```

**Comment by mgravell** [comment]
ah, slightly modified source code - you can see why I wouldn't know that :)

the *easiest* way to get a value out of a sp would be: to `select` it - then you can use `QuerySingle<int>` or whatever; I'm very curious as to what is happening in your case, though - I'll go ahead and see if I can make it break by invoking it a few million lines (I didn't do that yesterday because I thought the `CommandType` was the most likely issue)

**Comment by mgravell** [comment]
as a random aside; I'm trying to figure out whether or not we should *automatically* apply `CommandType.StoredProcedure` if the command wasn't specified and the command text consists purely of characters that look like object names  (probably something like [the "regular identifier" rules here](https://msdn.microsoft.com/en-us/library/ms175874.aspx), plus common db notation symbols like `.`, `[`, `]` etc. This would mean that:

    conn.Execute("dbo.[myStoredProc]", args); // works
    conn.Execute("dbo.[my stored proc]", args); // doesn't work
    conn.Execute("dbo.[my stored proc]", args, commandType: CommandType.StoredProcedure); // works

(the second one fails because it isn't a "regular identifier" - not 100% trivially obvious that it is a single object name)

Thoughts?

**Comment by mjeson** [comment]
I just created a Proof of Concept on a Console App. The bug didnt materialize. Will try to run it on the ASP.NET Core 1 next//

**Comment by mjeson** [comment]
I found the issue. Turns out I accidentally share a DapperParameter instance into two different SqlConnection that execute concurrently. The bug is on my side. No bug here!
