### ISSUE TITLE
Mariadb wrong type convertion uint

### ISSUE THREAD

**Issue by zokiad** [StackExchange/Dapper#753]
Hi,

Create a table BUG in mariadb 10.1.21:

```SQL
CREATE TABLE `BUG` (
  `IPAddress` int(10) unsigned DEFAULT NULL,
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```
Add value 2637637568 in IPAddress (> C# int limit)

In C# code:

```C#
    public class BUG
    {
        public long? IPAddress { get; set; }
    }
```

Launch a query with dapper:

```C#
 db.Query<BUG>(@"SELECT IPAddress FROM BUG");
```

**The value of BUG.IPAddress is < 0** 

***Workaround:***
` db.Query<BUG>(@"SELECT CAST(IPAddress AS INT) FROM BUG");`

**Comment by NickCraver** [comment]
Does this have the same behavior in ADO.NET? I'd imagine this is the behavior of their provider not being aware of the UNSIGNED directive (which has no direct mapped type in C#).

The types would be `unit` for alignment, or `BIGINT` in the DB for `long` mapping, does that make sense?

**Comment by zokiad** [comment]
With Entity Framework, it  works fine, no issue.

We use unsigned data type in DB to save space (a lot of columns).

**Comment by zokiad** [comment]
For more information, i try to debug:

In Dapper-master\Dapper\SqlMapper.cs line 948

```C#
                while (reader.Read())
                {
                    object val = func(reader);
		    if (val == null || val is T) {
                        yield return (T)val;
                    } else {
                        yield return (T)Convert.ChangeType(val, convertToType, CultureInfo.InvariantCulture);
                    }
                }
```
In debug, I try to read data of column define unsigned int in database:

> reader[0]	2637637568	object {uint}
> reader.GetFieldType(0)	{Name = "UInt32" FullName = "System.UInt32"}	System.Type {System.RuntimeType}

Value is correctly and type return UInt32 is also correctly.

I think the issue is in func method but I am losting in it.

**Comment by jeroenwalter** [comment]
We have the same issue.
We're trying to read an uint with the value 0xFFFFFFFF (Uint.MaxValue) from a SQLite database, 
When we map the column to an uint property via Dapper, Dapper fails with an OverflowException.
We think this is caused by the SqlMapper.cs that generates incorrect conversion code for conversion of integers to unsigned integers in the method FlexibleConvertBoxedFromHeadOfStack.
The wrong opcode is used, OpCodes.Conv_Ovf_I4_Un, which converts an unsigned to a signed integer, exactly the opposite what must be done... 
We expect Dapper to read an int64 and to convert it to uint32.
We were actually very surprised that we encountered this bug, this should've been caught via the unit tests, as uint.maxvalue is a bordercase.

**Comment by zokiad** [comment]
Yes, exactly. It's strange code. I think we need to create a specific case for unsigned from to convert to unsigned with OpCodes.Conv_Ovf_U4_Un or OpCodes.Conv_Ovf_U2_Un ...
Somebody, I start the modification ? else I try to modify and create a test to fix this issue. After, I hope my pull request will be accepted

**Comment by zokiad** [comment]
I cannot reproduce the issue. Perhaps after upgrade mariadb to 10.1.23 ?
