### ISSUE TITLE
Making the Example Query Work

### ISSUE THREAD

**Issue by ashes999** [StackExchange/Dapper#754]
Hi,

I'm trying to make [this example query](https://github.com/StackExchange/Dapper#execute-a-query-and-map-the-results-to-a-strongly-typed-list) work.  The query is:

`var dog = connection.Query<Dog>("select Age = @Age, Id = @Id", new { Age = (int?)null, Id = guid });`

I'm trying to avoid writing `SELECT * FROM TableName` in cases like this.  Does Dapper support this?

I have a similar case where I have a `Task` class (`Id`, `Description`, `OwnerId`, etc.) and a `Tasks` table. When I try `conn.Query<Task>("SELECT Where OwnerId = @ownerId", { ... })` I get back a list with one dummy object. Whatever I set in my query (in this case, `ownerId`) is the only populated value.

I also tried using the `Dapper.Contrib` package with [`Table("Tasks")]` to see if it's the table-name mapping. Didn't make a difference, though.

**Comment by mgravell** [comment]
can you clarify what you want? In SQL you can either select columns
explicitly ("select Id, Name, DateOfBirth from ...") or use a wildcard
("select * from .. "). If you don't want to use a wildcard... be explicit!
But: that's SQL.

What is it you wanted  to write?

**Comment by ashes999** [comment]
Hi Marc,

The example query from README.md seems to suggest that if you have a `Dog` class and (presumably) a `Dogs` table, you can write:

`connection.Query<Dog>("select Age = @Age, Id = @Id", {...});`

... and Dapper will return a collection of `Dog` objects. 

Am I misreading this query? Is it saying "select the age and ID?" I thought those conditions were more like "where" clauses, eg. that the query is equivalent to `select * from Dogs WHERE Age = @Age and Id = @Id`.

**Comment by mgravell** [comment]
yes, you're misreading  the query. That populates 1 row based on the
parameters - it doesn't even touch a table.

On 25 Apr 2017 9:19 p.m., "Ashiq A." <notifications@github.com> wrote:

Hi Marc,

The example query from README.md seems to suggest that if you have a Dog
class and (presumably) a Dogs table, you can write:

connection.Query<Dog>("select Age = @Age, Id = @Id", {...});

... and Dapper will return a collection of Dog objects.

Am I misreading this query? Is it saying "select the age and ID?" I thought
those conditions were more like "where" clauses, eg. that the query is
equivalent to select * from Dogs WHERE Age = @Age and Id = @Id.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/754#issuecomment-297152745>,
or mute the thread
