### ISSUE TITLE
The latest source code can't open by vs2015

### ISSUE THREAD

**Issue by niufwshd** [StackExchange/Dapper#830]
I clone the source code by vs2015's integrated git plugin,but an error dialog displayed: ms xml namespace error. I tried to add 'xmlns="http://schemas.microsoft.com/developer/msbuild/2003"' to the .project file's root element.but another error occure: "packagereference's  Version property" error. Did someone come across this problem.please help me ,thank you first!

**Comment by mgravell** [comment]
yes, this is quite likely.

Since we target multiple frameworks it is ideal for us to us the new csproj
format with multi-targetting and packaging built in.

This format is not supported in VS2017.

Options:

- use VS2017 (the free versions should be fine)
- use dotnet cli
- create a project / solution locally

I don't propose to support VS2015 solutions separately inside the project.
That adds a maintenance burden.

**Comment by niufwshd** [comment]
Thank you very much mgravell. I will install one vs2017 version  and explore the great project.
Thx a lot!

**Comment by NickCraver** [comment]
Closing out to cleanup, note that https://github.com/StackExchange/Dapper/pull/836 will update the minimum version of Visual Studio 2017 to 15.3.0, since it's needed to build `netstandard2.0` packages.
