### ISSUE TITLE
System.Data.SqlClient SqlConnection has a connection leak on docker container. 

### ISSUE THREAD

**Issue by turgayozgur** [StackExchange/Dapper#835]
Dapper 1.50.2 depend to System.Data.SqlClient version 4.1.0. This version has a connection leak problem. Please update System.Data.SqlClient from (4.1.0) to (>=4.3.1).

https://github.com/dotnet/corefx/issues/13422

**Comment by NickCraver** [comment]
This isn't a problem with Dapper directly, but the reference the end user is using for `SqlClient`. A user can directly include 4.3.1 if they wish, from a library standpoint it's better when we're available to a wider variety of clients (e.g. not forcing upgrades for those not affected by issues).

That being said, this will happen as part of `netstandard2.0` anyway, since it's a simpler dependency graph, but I'm focusing on finishing off a few other libraries first.

**Comment by NickCraver** [comment]
This is done in the latest alpha: https://www.nuget.org/packages/Dapper/1.50.4-alpha1-00070 (we're depending on 4.4.0 now)
