### ISSUE TITLE
Is there any way to read same result multiple times 

### ISSUE THREAD

**Issue by ehsaanwelcome** [StackExchange/Dapper#853]
I want to read result once as DapperRow "dapper.Read()" and same result with Type "dapper.Read<T>()".
Is there a way to achieve that?

**Comment by NickCraver** [comment]
I am not understanding the question, can you provide a scenario for this? In short: if you need it twice, store it for use twice as a variable. What shape that takes might vary but the basic approach wouldn't change. Dapper itself is streaming from ADO.NET interfaces, so that's just not the correct place to do it (e.g. in the library).
