### ISSUE TITLE
Literal parameter can replace in tablename or oder by clause？

### ISSUE THREAD

**Issue by strongdevx** [StackExchange/Dapper#864]
this is work fine:
```
var result = Queryl<object>("Conn_Sqlserver", "select top {=top} * from  product",new { top=10});
```

but not work like this:

```
var result = Queryl<object>("Conn_Sqlserver", "select top {=top} * from  {=table_name} order by {=orderby}",new { top=10,  table_name="products", orderby="id desc" });
```

**Comment by mgravell** [comment]
No, is the short answer. Literal support is intentionally very limited,
because you very quickly start getting into quagmire where people are
opening up injection attack surfaces, etc. To "fix" it at the library level
we'd need to apply escape syntax, but that varies both by provider and per
language element (string escaping is different to table name escaping, for
example).

So: no. You'll have to build that sql manually via composition.

On 19 Oct 2017 10:53 a.m., "strongdevx" <notifications@github.com> wrote:

this is work fine:

var result = Queryl<object>("Conn_Sqlserver", "select top {=top} *
from  product",new { top=10});

but not work like this:

var result = Queryl<object>("Conn_Sqlserver", "select top {=top} *
from  {=table_name} order by {=orderby}",new { top=10,
table_name="products", orderby="id desc" });

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/864>, or mute the thread

**Comment by strongdevx** [comment]
@mgravell  Thanks for your reply.
