### ISSUE TITLE
Dapper Sybase Parameter replacement broken

### ISSUE THREAD

**Issue by giorgiozoppi** [StackExchange/Dapper#868]
We have tries both with Dapper and DapperControb.Extension and it happens that @Name column not found. We  suspect that for sybase the function SetupParameters is not working anymore.
We are willling to help. 
Our setup is sybase anywhere 16. 
.......mainproram
            try
            {

                using (var connection = new SAConnection(connectionString))
                {
                    connection.Open();
                    Agenda agenda = new Agenda();
                    agenda.Name = "Giorgio";
                    agenda.Surname = "Zoppi";
                
                    string sqlQuery = @"INSERT INTO Agenda(Name, Surname) VALUES (@Name,@Surname);";
                    connection.Execute(sqlQuery,
                     agenda);
                   

                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
                throw e;
            }

        }
    }
}

**Comment by mgravell** [comment]
Is it possible that Sybase requires positional parameters? Try using ?Name?
instead of @Name - dapper interprets "?foo?" as "add a parameter with the
value from 'foo', but use positional parameters by replacing ?foo? with
just a single question mark".


On 21 Oct 2017 11:09 p.m., "giorgiozoppi" <notifications@github.com> wrote:

We have tries both with Dapper and DapperControb.Extension and it happens
that @name <https://github.com/name> column not found. We suspect that for
sybase the function SetupParameters is not working anymore.
We are willling to help.
Our setup is sybase anywhere 16.
.......mainproram
try
{

            using (var connection = new SAConnection(connectionString))
            {
                connection.Open();
                Agenda agenda = new Agenda();
                agenda.Name = "Giorgio";
                agenda.Surname = "Zoppi";

                string sqlQuery = @"INSERT INTO Agenda(Name, Surname)
VALUES (@Name,@Surname);";
                connection.Execute(sqlQuery,
                 agenda);


            }
        }
        catch (Exception e)
        {
            Console.WriteLine(e.Message);
            throw e;
        }

    }
}

}

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/868>, or mute the thread

**Comment by mgravell** [comment]
(obviously replace @Surname with ?Surname? too)

**Comment by giorgiozoppi** [comment]
How does the replacement dapper? The code arrives directly to the last ExecuteNoQuery without replacing. I will dig into, because we need to switch to the Ado.net (DataSet/DataTable) to something OOP and mounting EF for sybase we will experience the same problems.

**Comment by giorgiozoppi** [comment]
Gotta try your thing.

**Comment by giorgiozoppi** [comment]
Yes it works. You saved my week. Dapper makes easy many things. So we have created an extension for contrib to solve the insert and update and it works as well. I think it is not a dapper problem we can close this issue for now. I will provide patches for Contrib during the week until it is not completely tested we keep the dual approach.
