### ISSUE TITLE
openasync not available for Idbconnection

### ISSUE THREAD

**Issue by karunagoyal** [StackExchange/Dapper#872]
I am getting db connection using idbconnection as below:
```c#
public IDbConnection Create()
{
    return new SqlConnection("connection string here");
}
```

when I try to do open connection async way, there is nothing available in dapper
```c#
using (var connection = ConnectionFactory.Create())
{
    connection.Open();
    return await connection.QueryAsync<T>(query, input, transaction: dbTransaction, commandType: commandType);
}
```
Looks like without this my method never returns. It is blocked forever.
Can you please suggest?

**Comment by NickCraver** [comment]
A few questions:
1. Is this a SQL Server connection or something else like MySQL?
2. Have you tried not opening the connection? Dapper will handle this for you, via `.OpenAsync()` to boot.

**Comment by NickCraver** [comment]
A better error message for this is thrown as of 1.50.5 :)

**Comment by agoodwin** [comment]
I hope I'm not doing something annoying by commenting on a closed issue, but this question is quite relevant to your comment @NickCraver and it's so minor I don't think it's worth opening a new issue for it.

As I understand it, if you want to do several queries on the same connection you should mange the connection yourself – i.e. in this case you shouldn't leave it to Dapper to use `OpenAsync`, as per your suggestion above, because Dapper will then open and close the connection for every query unnecessarily.

So the question is, do you have an alternative suggestion for the case when you're managing the connection yourself? To be honest I'm not having the same issue as the OP, so I'm just using the synchronous `Open` method to keep things clean and avoid casting my `IDbConnection`, but I'm curious if you think there's a better approach.

**Comment by VictorioBerra** [comment]
@NickCraver Digging this up, any recommendations for using `OpenAsync` on `IDbConnection`?
