### ISSUE TITLE
Are there any more efficient API in "Reader-Mapping-Cache"?

### ISSUE THREAD

**Issue by NMSAzulX** [StackExchange/Dapper#874]
Here is the source code of  [SqlBuffer](http://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlBuffer.cs,178f8aa03d136d6f).
It looks like : DataReader->GetValue->GetValueInternal->SqlBuffer
So,we can use the API  such as  GetInt64, GetInt32, GetString and so on  to instead of GetValue, They're more efficient！

**Comment by NMSLanX** [comment]
Anyone here?

**Comment by mgravell** [comment]
Yes, but we're busy and frankly yesterday was not a great day. I need to
have a look - note that reference source shouldn't be relied upon, I need
to look at disassembled IL or the .net core source (or both). But I seem to
recall that this usage was not as useful as you'd expect, especially
between different providers.

On 3 Nov 2017 1:30 a.m., "Hu" <notifications@github.com> wrote:

Anyone here?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/874#issuecomment-341603963>,
or mute the thread

**Comment by NMSLanX** [comment]
Oh.. Thank you.
