### ISSUE TITLE
Cannot use spaces or tabs before procedure name

### ISSUE THREAD

**Issue by FromaszBlack** [StackExchange/Dapper#891]
I've found the following issue: adding spaces or tabs before procedure name causes an error.

`connection.Execute("  proc1", new { usernName = "s" }, commandType: CommandType.StoredProcedure);`

> Could not find stored procedure '  proc1'.

Works after removing initial spaces and tabs.
No problem with SQL queries.

**Comment by mgravell** [comment]
does your stored procedure actually have white characters at the start of
the name?

**Comment by FromaszBlack** [comment]
No.
I wanted to write my query in multiple lines.
```
return c.Query<RequestWarehouseModel>(@"
    Database1.dbo.Proc1",
    new { userName }, commandType: CommandType.StoredProcedure).SingleOrDefault();
```

For select query it works:
```
return c.Query<Table1Model>(@"
    SELECT
        r.ID,
        r.Col1,
        r.Col2,
        r.Date1,
        r.Date2,
        r.Date3
    FROM
        Database1.dbo.Table1 AS r
    ORDER BY
        r.Col1 DESC").ToList();
```

**Comment by rhubley** [comment]
Can you use

    Conn.Query(@“
        exec proc1”, new { username});

**Comment by mgravell** [comment]
The exec usage shown doesn't pass the parameter down, note!

Ultimately, SQL batches don't care about whitespace - but individual names:
do. Fortunately, c# doesn't - so I suggest you leave the whitespace to c#
here:

    conn.Execute(
        "SomeName",
        args, commandType: ...);

On 29 Nov 2017 10:28 p.m., "Richard Hubley" <notifications@github.com>
wrote:

Can you use

Conn.Query(@“
    exec proc1”, new { username});

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/891#issuecomment-348018093>,
or mute the thread
