### ISSUE TITLE
Dapper mapping alphabetically causing datatype mismatch in Access.

### ISSUE THREAD

**Issue by goyzhang** [StackExchange/Dapper#911]
Hello, 
I'm using dapper to insert some data into my access DB. The connectionstring is like
`@"Provider=Microsoft.ACE.OLEDB.15.0;Data Source=./Database.accdb;Persist Security Info=True;Jet OLEDB:Database Password=123"`.
The entity , for example , is like following:
```
public class MyClass
{
    public int MyNumber { get; set; }
    public DateTime MyDate { get; set; }
}
```
The command got datetype error when :
```
MyClass myClass = new MyClass()
            {
                MyNumber = 1,
                MyDate = DateTime.Today
            };
connection.Execute("INSERT INTO MyTable (MyNumber, MyDate) VALUES (@MyNumber, @MyDate)", myClass); //Non-alphabet order
```
But works fine if I change it to:
```
connection.Execute("INSERT INTO MyTable (MyDate,MyNumber) VALUES (@MyDate,@MyNumber)", myClass);
//Alphabet order
```
which is the default alphabet way.
It also works if I use a anonymous object without placing fields alphabetically as long as the object follow the sql statement:
```
connection.Execute("INSERT INTO MyTable (MyNumber,MyDate) VALUES (@MyNumber,@MyDate)", new{MyNumber = 1,MyDate = DateTime.Today}); 
//anonymous object overwrites the default order of myClass
```

Is this because Dapper's mapping reflection takes properties as DbCommand parameters in an alphabet order? Ideally, the command should be successful not matter how fields are ordered.

In practice, I was using Unicode fieldname, but the result is the same, the statement has to match the entity's "potential" order.  Anyone got the same issue?

**Comment by mgravell** [comment]
My guess is that the access driver is switching to positional parameters
(not named parameters), but not doing it in a sane way. In which case I
would say: dammit, that's a bad thing to do.

Fortunately, dapper supports pseudo-positional parameters.

Please could you try changing `@foo` to `?foo?` for each of your
parameters? Dapper interprets this by switching to pure positional mode
(replacing all the parameter tokens with just ?) - and knows to add the
parameters in the right order.

**Comment by goyzhang** [comment]
@mgravell  Changing to `?foo?` works. But `@foo` always gives me  a "fixed" inside order without respect to the sqlstatements,resulting in a mispositioned INSERT or even a type mismatch error.  
What's wrong with `@`?

**Comment by mgravell** [comment]
Dapper assumes that the db provider it is using isn't being stupid and
assumes that if the provider offers named parameter support, the provider
knows how named parameters work. It turns out that the accrss provider
doesn't meet this low bar. Basically, given the following:

command text = "select @foo, @bar"

add param "bar" with value 123

add param "foo" with value 456

Then what the access driver does is:

command text = "select ?, ?"

add param with value 123

add param with value 456

---

This erasure of all names obviously has the effect of reversing the
intended parameter order, so it is incredibly dependent on the parameters
being added in a specific order. This is not normal for named parameters,
and dapper doesn't attempt to force any specific order on the parameters.

IMO what the access driver should have done is - if it detects named
parameters: add the parameters to the underlying connection *in the order
in which they originally appeared in the query*. However this is very
unlikely to be fixed in the access driver.

The other thing we could potentially do is make dapper add parameters in
the order defined by the position of that named token in the query. Perhaps
not unreasonable, just... usually unnecessary.

On 26 Dec 2017 9:14 a.m., "goyzhang" <notifications@github.com> wrote:

@mgravell <https://github.com/mgravell> Changing to ?foo? works. But @foo
always gives me a "fixed" inside order without respect to the
sqlstatements,resulting in a mispositioned INSERT or even a type mismatch
error.
What's wrong with @?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/911#issuecomment-353943455>,
or mute the thread

**Comment by goyzhang** [comment]
I see , even with the newest provider, Microsoft.ACE.OLEDB.15.0 is stuipd.
