### ISSUE TITLE
SQLite: IEnumerable insert performance is 38,000 times as slow as direct SQL statement

### ISSUE THREAD

**Issue by DumpsterDoofus** [StackExchange/Dapper#926]
## Background

There have been previous reports of poor performance inserting multiple rows (https://github.com/StackExchange/Dapper/issues/785), and I've anecdotally seen moderate slowness on MS SQL batch inserts, but it wasn't bad enough to complain about.

However, on SQLite, the write performance is so mindbogglingly bad (almost 40,000 times as slow as handwritten code, see below repro steps) that I've been forced to abandon using Dapper in an app which *simply writes a couple dozen rows to an SQLite database*.

I'd appreciate feedback on whether I'm totally misusing Dapper, or if any workarounds are possible.

## Minimal Repro Steps

1. Create a new .NET Framework (in this case, v4.6.1) console app:

![1](https://user-images.githubusercontent.com/6626631/35200614-a5bc619c-fec6-11e7-889f-05c84c1e5f3c.PNG)

2. Add NuGet references to Dapper (v1.50.4.0) and System.Data.SQLite (v1.0.106, which as a side effect will add 4 other NuGet dependencies):

![2](https://user-images.githubusercontent.com/6626631/35200623-b6fc828e-fec6-11e7-921d-fa7b17bf6f9a.PNG)

3. Run the following `Main` method, which 
    - Creates a database with a table with a single column 
    - Writes a list of `i` records to the table, timing the results for each `i`:

```
using System;
using System.Data.SQLite;
using System.Diagnostics;
using System.Linq;
using Dapper;

namespace DapperPerfTest
{
    class Program
    {
        static void Main()
        {
            SQLiteConnection.CreateFile("./PerfTest.sqlite");
            using (var sqLiteConnection = new SQLiteConnection("Data Source=./PerfTest.sqlite;Version=3;"))
            {
                sqLiteConnection.Open();
                sqLiteConnection.Execute(@"CREATE TABLE IF NOT EXISTS [Test] ([Thing] INTEGER NOT NULL)");
                var stopwatch = new Stopwatch();
                for (var i = 1; i <= 50; i++)
                {
                    stopwatch.Start();
                    sqLiteConnection.Execute(@"INSERT INTO Test (Thing) VALUES (@Thing)", Enumerable.Repeat(new Test{Thing = 1}, i));
                    stopwatch.Stop();
                    Console.WriteLine($"Writing {i} records took {stopwatch.ElapsedMilliseconds} milliseconds.");
                    stopwatch.Reset();
                }
            }
        }
    }

    public class Test
    {
        public int Thing { get; set; }
    }
}
```

Here is a graph of performance:

![3](https://user-images.githubusercontent.com/6626631/35200671-437fda4e-fec7-11e7-9ad2-308df7ba4813.PNG)

A regression fit shows it's approximately linear (as suggested by eyeing the above graph), at ~160 milliseconds per row.

In contrast, the following handwritten query inserts 40,000 rows in 200 milliseconds when run manually:

```
insert into Test 
(Thing)
values
(1), 
-- Repeated 40,000 times
(1)
```

**This is over 38,000 times faster than the equivalent Dapper query.** Needless to say, this makes Dapper useless for real applications that write to SQLite databases.

## Notes

The above repro steps are as minimal as I could get (writing integers to a single column). The poor performance is also reproducible on .NET Core, where I originally noticed it. Replacing the `INTEGER` column with `NVARCHAR` or other data types doesn't seem to make a difference in speed (they're all equally slow).

**Comment by mgravell** [comment]
Dapper does not concatenate commands, and cannot do so: most providers have
a maximum parameter count that is prohibitive. And frankly - Dapper doesn't
want to be involved in large-scale SQL rewriting. For this to be a
like-for-like comparison of Dapper, your baseline test should be:

- loop over the Enumerable.Range
- execute a command object once per item via a sqlite command object

What you are most likely seeing is round-trip time: latency. Now, there are
sometimes vendor-specific ways around that. For example, on SQL Server, we
could talk about SqlBulkCopy, or we could talk about "MARS" and overlapped
pipelined commands. But I don't think those exist for sqlite.

There is one other possibility here, which is that we're talking about
mandatory prepared statements and the prepare overhead. To check that, a
comparison baseline loop should create a single parameterized query, call
Prepare on or once, the run the loop that sets the parameter values and
calls ExecuteNonQuery each time. Now: if *that* timing is significantly
better than Dapper, then *in that scenario* there is a potential change
that Dapper could make to improve things. In fact, I'd be genuinely
interested in the results of that test. It all comes down to mandatory vs
optional command preparation. This is a topic I have discussed here
http://blog.marcgravell.com/2017/12/dapper-prepared-statements-and-car-tyres.html
- it also hints at the change we could potentially make in Dapper for this
specific scenario - the enumerable arg to Execute.


On 22 Jan 2018 1:02 am, "Peter Richter" <notifications@github.com> wrote:

Background

There have been previous reports of poor performance inserting multiple
rows (#785 <https://github.com/StackExchange/Dapper/issues/785>), and I've
anecdotally seen moderate slowness on MS SQL batch inserts, but it wasn't
bad enough to complain about.

However, on SQLite, the write performance is so mindbogglingly bad (see
below repro steps) that I've been forced to abandon using Dapper in an app
which *simply writes a couple dozen rows to an SQLite database*.

I'd appreciate feedback on whether I'm totally misusing Dapper, or if any
workarounds are possible.
Minimal Repro Steps

   1. Create a new .NET Framework (in this case, v4.6.1) console app:

[image: 1]
<https://user-images.githubusercontent.com/6626631/35200614-a5bc619c-fec6-11e7-889f-05c84c1e5f3c.PNG>

   1. Add NuGet references to Dapper (v1.50.4.0) and System.Data.SQLite
   (v1.0.106, which as a side effect will add 4 other NuGet dependencies):

[image: 2]
<https://user-images.githubusercontent.com/6626631/35200623-b6fc828e-fec6-11e7-921d-fa7b17bf6f9a.PNG>

   1. Run the following Main method, which
      - Creates a database with a table with a single column
      - Writes a list of i records to the table, timing the results for
      each i:

using System;
using System.Data.SQLite;
using System.Diagnostics;
using System.Linq;
using Dapper;

namespace DapperPerfTest
{
    class Program
    {
        static void Main()
        {
            SQLiteConnection.CreateFile("./PerfTest.sqlite");
            using (var sqLiteConnection = new SQLiteConnection("Data
Source=./PerfTest.sqlite;Version=3;"))
            {
                sqLiteConnection.Open();
                sqLiteConnection.Execute(@"CREATE TABLE IF NOT EXISTS
[Test] ([Thing] INTEGER NOT NULL)");
                var stopwatch = new Stopwatch();
                for (var i = 1; i <= 50; i++)
                {
                    stopwatch.Start();
                    sqLiteConnection.Execute(@"INSERT INTO Test
(Thing) VALUES (@Thing)", Enumerable.Repeat(new Test{Thing = 1}, i));
                    stopwatch.Stop();
                    Console.WriteLine($"Writing {i} records took
{stopwatch.ElapsedMilliseconds} milliseconds.");
                    stopwatch.Reset();
                }
            }
        }
    }

    public class Test
    {
        public int Thing { get; set; }
    }
}

Here is a graph of performance:

[image: 3]
<https://user-images.githubusercontent.com/6626631/35200671-437fda4e-fec7-11e7-9ad2-308df7ba4813.PNG>

A regression fit shows it's approximately linear (as suggested by eyeing
the above graph), at ~160 milliseconds per row.

In contrast, the following handwritten query inserts 40,000 rows in 200
milliseconds when run manually:

insert into Test
(Thing)
values
(1),
-- Repeated 40,000 times
(1)

*This is over 38,000 times faster than the equivalent Dapper query.*
Notes

The above repro steps are as minimal as I could get (writing integers to a
single column). The poor performance is also reproducible on .NET Core,
where I originally noticed it.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/StackExchange/Dapper/issues/926>, or mute the thread

**Comment by mgravell** [comment]
Some additional context here: sqlite has aggressive transaction semantics that can impact the performance of lots of inserts; according to http://www.sqlite.org/faq.html#q19 you might improve the performance if you create an explicit transaction and pass that transaction into all of the methods

**Comment by JaseRandall** [comment]
>  you might improve the performance if you create an explicit transaction and pass that transaction into all of the calls

Absolutely! If you don't wrap all your inserts in a transaction then SQLite will wrap every insert with it's own transaction and it will be extremely slow.

Try the code below which did 40,000 inserts in 380 milliseconds onto a SSD:
```
using System;
using System.Data.SQLite;
using System.Diagnostics;
using Dapper;

namespace DapperPerfTest
{
    class Program
    {
        static void Main()
        {
            SQLiteConnection.CreateFile("./PerfTest.sqlite");
            using (var sqLiteConnection = new SQLiteConnection("Data Source=./PerfTest.sqlite;Version=3;"))
            {
                sqLiteConnection.Open();
                var tr = sqLiteConnection.BeginTransaction();
                sqLiteConnection.Execute(@"CREATE TABLE IF NOT EXISTS [Test] ([Thing] INTEGER NOT NULL)");
                var stopwatch = new Stopwatch();
                var numRecords = 40000;
                var objs = new object[numRecords];
                for (var i = 0; i <= numRecords - 1; i++)
                {
                    objs[i] = new {Thing = i};
                }

                stopwatch.Start();
                for (var i = 0; i <= numRecords - 1; i++)
                {
                    sqLiteConnection.Execute(@"INSERT INTO Test (Thing) VALUES (@Thing)", objs[i]);
                }
                tr.Commit();
                stopwatch.Stop();
                
  
                Console.WriteLine($"Writing {numRecords} records took {stopwatch.ElapsedMilliseconds} milliseconds.");
            }
        }
    }

    public class Test
    {
        public int Thing { get; set; }
    }
}
```

I've been using Dapper.Contrib but I might have to give this code a run for bulk inserts.

**Comment by mgravell** [comment]
Thanks @JaseRandall  - I suspected that would make a big difference, but since I'm not a sqlite expert I had to rely on anecdotal evidence. With this update, @DumpsterDoofus, I'm going to consider this "closed", since it seems clear that this is a sqlite feature with a simple workaround. If you disagree, please let me know and we can reopen.
